# **<span style="color:#48B3AF; font-family: 'Courier New"> TRANSFORM </span>**

## **<span style="color:#476EAE; font-family: 'Courier New"> Resources </span>**

In [51]:
# Infrastructure
import os
from dotenv import load_dotenv
import pandas as pd
import numpy as np

# Mappings
bool_map = {"SI": True, "Si": True, "NO": False, "No": False}

### **<span style="color:#A7E399; font-family: 'Courier New"> Republic of Moldova </span>**

In [52]:
# Load files for transformation
lista_dc_cnam = pd.read_csv("transforming/lista_dc_cnam.csv", dtype=str)
dci = pd.read_csv("transforming/dci.csv", dtype=str)
cim = pd.read_csv("transforming/cim.csv", dtype=str)

In [53]:
# Remove leading and trailing spaces
lista_dc_cnam = lista_dc_cnam.map(lambda x: x.strip() if isinstance(x, str) else x)
dci = dci.map(lambda x: x.strip() if isinstance(x, str) else x)
cim = cim.map(lambda x: x.strip() if isinstance(x, str) else x)

In [55]:
display(lista_dc_cnam.head(2))

,Grupa maladiilor pentru compensare,Cod DCI,Denumirea Comuna Internationala (DCI),Doza în SI MC,Cod DC,Denumirea comercială (DC),Doza,Forma farmaceutică,Divizarea,Ţara,Firma producătoare,Număr de înregistrare,Data înregistrării,Cod ATC,Cod medicament (Catalogul național de prețuri),is_child_rate,coverage_type,Cod DCI_sec,Cod DC_sec
0,Pentru tratamentul maladiilor aparatului locom...,060,ACECLOFENACUM,100,0601001,Aceclofenac-BP,100 mg,comprimate,N10x3,Republica Moldova,"Balkan Pharmaceuticals SRL, SC",26519,10.09.2020,M01AB16,9200900714,False,Partial,NaN,NaN
1,Pentru tratamentul maladiilor aparatului locom...,060,ACECLOFENACUM,100,0601002,Airtal,100 mg,comp. film.,N10x6,Ungaria,Gedeon Richter PLC,25086,29.10.2018,M01AB16,0109370013,False,Partial,NaN,NaN

In [16]:
display(dci.head(2))

,Nr. d/o,Denumirea comună internațională (DCI),Doza,Forma farmaceutică,Rata de compensare din mediana prețurilor,"Suma fixă compensată per unitate de măsură (MDL), inclusiv TVA","Suma fixă compensată per unitate de măsură (MDL), fără TVA",Cod CIM \nde diagnostic/limitare indicație,Durata tratamentului,Destinat
0,1.0,ACECLOFENACUM,100 mg,"comprimate, comprimate filmate",1,2.33,2.16,"M069-Artrita reumatoida, fara precizare\nM199-...",cronic,adulți/copii
1,NaN,ACECLOFENACUM,100 mg,"comprimate, comprimate filmate",1,2.33,2.16,"M069-Artrita reumatoida, fara precizare\nM109-...",episodic,adulți

In [17]:
display(cim.head(2))

,CodDiagnostic,DenDiagnostic,DenSubClasaDiagnostic,DenClasaDiagnostic
0,A000,"Holera cu Vibrio cholerae,biovar cholerae",Boli infectioase intestinale,Boli infectioase si parazitare
1,A001,"Holera cu Vibrio cholerae eltor,biovar eltor",Boli infectioase intestinale,Boli infectioase si parazitare

In [ ]:
dc_cim = lista_dc_cnam.merge(cim, )

### **<span style="color:#A7E399; font-family: 'Courier New"> Spain </span>**

In [56]:
# Load files for transformation
df_presentation = pd.read_csv("transforming/df_presentation.csv", dtype=str)
df_formulation = pd.read_csv("transforming/df_formulation.csv", dtype=str)
df_coverage = pd.read_csv("transforming/df_coverage.csv", dtype=str)

In [57]:
# Remove leading and trailing spaces
df_presentation = df_presentation.map(lambda x: x.strip() if isinstance(x, str) else x)
df_formulation = df_formulation.map(lambda x: x.strip() if isinstance(x, str) else x)
df_coverage = df_coverage.map(lambda x: x.strip() if isinstance(x, str) else x)

In [58]:
# Boolean transformations

for col in [
    "¿Comercializado?",
    "¿Triangulo Amarillo?",
    "¿Problemas de suministro?",
    "¿Sustituible?",
    "¿Afecta conducción?"
]:
    if col in df_presentation.columns:
        df_presentation[col] = df_presentation[col].map(bool_map)

In [59]:
display(df_presentation.head(2))

,Nº Registro,Cod. Nacional,Presentación,Laboratorio,Fecha Aut.,Estado,Fecha Estado,Cód. ATC,Principios Activos,¿Comercializado?,¿Triangulo Amarillo?,Observaciones,¿Sustituible?,¿Afecta conducción?,¿Problemas de suministro?
0,81510,713926,"ATROPINA AGUETTANT 0,1 MG/ML SOLUCION INYECTAB...",Laboratoire Aguettant,09/12/2016,Autorizado,01/02/2017,A03BA01,ATROPINA SULFATO,True,False,Uso Hospitalario,NaN,True,False
1,81513,713937,"ATROPINA AGUETTANT 0,2 MG/ML SOLUCION INYECTAB...",Laboratoire Aguettant,12/12/2016,Autorizado,22/02/2017,A03BA01,ATROPINA SULFATO,True,False,Uso Hospitalario,NaN,True,False

In [60]:
for col in [
    "¿Comercializado?",
    "¿Triangulo Amarillo?",
    "¿Problemas de suministro?",
    "¿Sustituible?",
    "¿Afecta conducción?"
]:
    if col in df_formulation.columns:
        df_formulation[col] = df_formulation[col].map(bool_map)

In [62]:
display(df_formulation.head(2))

,Nº Registro,Medicamento,Laboratorio,Fecha Aut.,Estado,Fecha Estado,Cód. ATC,Principios Activos,Nº P. Activos,¿Comercializado?,¿Triangulo Amarillo?,Observaciones,¿Sustituible?,¿Afecta conducción?,¿Problemas de suministro?
0,88639,2LARTH GLÓBULOS,"Labo´Life España, S.A.",15/02/2023,Autorizado,16/02/2023,V03AX,"INTERLEUCINA 1 C10, INTERLEUCINA 1 C17, INTERL...",12,True,False,Sin Receta,NaN,False,False
1,88647,2LC1 GLÓBULOS,"Labo´Life España, S.A.",15/02/2023,Autorizado,16/02/2023,V03AX,"DESOXIRRIBONUCLEICO ACIDO K200, INTERLEUCINA 1...",41,True,False,Sin Receta,NaN,False,False

In [63]:
for col in [
    "Situación de financiación"
]:
    if col in df_coverage.columns:
        df_coverage[col] = df_coverage[col].map(bool_map)

In [64]:
display(df_coverage.head(2))

,Código nacional,Principio activo o asociación*,Nombre del medicamento,Situación de financiación,Tipo de medicamento,Más Información
0,600001,DOXAZOSINA,DOXAZOSINA NEO TEVA-RATIOPHARM 4 mg COMPRIMIDO...,True,Genérico,NaN
1,600002,ACETILCISTEINA,ACETILCISTEINA PENSA 600 mg POLVO PARA SOLUCIO...,True,Genérico,NaN

In [83]:
df_full = pd.merge(df_presentation, df_coverage, left_on='Cod. Nacional', right_on='Código nacional', how='outer')
df_full = pd.merge(df_full, df_formulation[["Nº Registro", "Medicamento", "Laboratorio", "Fecha Aut.", "Estado",  "Fecha Estado", "Cód. ATC", "Principios Activos", "Nº P. Activos"]], left_on='Nº Registro', right_on='Nº Registro', how='outer')
df_full.head(2)
df_full[df_full["Situación de financiación"] == True].head(2)

,Nº Registro,Cod. Nacional,Presentación,Laboratorio_x,Fecha Aut._x,Estado_x,Fecha Estado_x,Cód. ATC_x,Principios Activos_x,¿Comercializado?,...,Tipo de medicamento,Más Información,Medicamento,Laboratorio_y,Fecha Aut._y,Estado_y,Fecha Estado_y,Cód. ATC_y,Principios Activos_y,Nº P. Activos
5,00129001,848226,"AZOPT 10 mg/ml COLIRIO EN SUSPENSION, 1 frasco...",Novartis Europharm Limited,05/05/2000,Autorizado,05/05/2000,S01EC04,BRINZOLAMIDA,True,...,NaN,NaN,AZOPT 10 mg/ml COLIRIO EN SUSPENSION,Novartis Europharm Limited,05/05/2000,Autorizado,05/05/2000,S01EC04,BRINZOLAMIDA,1
6,00130001,903955,"ORGALUTRAN 0,25 MG/0,5 ML SOLUCION INYECTABLE,...",Organon N.V.,17/01/2001,Autorizado,17/01/2001,H01CC01,GANIRELIX,True,...,NaN,NaN,"ORGALUTRAN 0,25 MG/0,5 ML SOLUCION INYECTABLE",Organon N.V.,17/01/2001,Autorizado,17/01/2001,H01CC01,GANIRELIX,1

In [84]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67253 entries, 0 to 67252
Data columns (total 29 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Nº Registro                     67202 non-null  object
 1   Cod. Nacional                   67202 non-null  object
 2   Presentación                    67202 non-null  object
 3   Laboratorio_x                   67202 non-null  object
 4   Fecha Aut._x                    67202 non-null  object
 5   Estado_x                        67202 non-null  object
 6   Fecha Estado_x                  67202 non-null  object
 7   Cód. ATC_x                      67202 non-null  object
 8   Principios Activos_x            67202 non-null  object
 9   ¿Comercializado?                67202 non-null  object
 10  ¿Triangulo Amarillo?            67202 non-null  object
 11  Observaciones                   67202 non-null  object
 12  ¿Sustituible?                   0 non-null      object
 13  ¿Afecta conducción?             67202 non-null  object
 14  ¿Problemas de suministro?       67202 non-null  object
 15  Código nacional                 50857 non-null  object
 16  Principio activo o asociación*  31365 non-null  object
 17  Nombre del medicamento          50857 non-null  object
 18  Situación de financiación       19485 non-null  object
 19  Tipo de medicamento             18993 non-null  object
 20  Más Información                 0 non-null      float64
 21  Medicamento                     67202 non-null  object
 22  Laboratorio_y                   67202 non-null  object
 23  Fecha Aut._y                    67202 non-null  object
 24  Estado_y                        67202 non-null  object
 25  Fecha Estado_y                  67202 non-null  object
 26  Cód. ATC_y                      67202 non-null  object
 27  Principios Activos_y            67202 non-null  object
 28  Nº P. Activos                   67202 non-null  object
dtypes: float64(1), object(28)
memory usage: 14.9+ MB

In [82]:
df_full[df_full["Cód. ATC"] == 'A05AA02'][0:2]

,Nº Registro,Cod. Nacional,Presentación,Laboratorio,Fecha Aut.,Estado,Fecha Estado,Cód. ATC,Principios Activos,¿Comercializado?,...,Observaciones,¿Sustituible?,¿Afecta conducción?,¿Problemas de suministro?,Código nacional,Principio activo o asociación*,Nombre del medicamento,Situación de financiación,Tipo de medicamento,Más Información
6760,85534,607383,ACIDO URSODESOXICOLICO GRINDEKS 250 MG CAPSULA...,Grindeks As,20/11/2020,Anulado,24/03/2026,A05AA02,URSODEOXICOLICO ACIDO,False,...,Medicamento Sujeto A Prescripción Médica,NaN,False,False,607383,URSODEOXICOLICO ACIDO,ACIDO URSODESOXICOLICO GRINDEKS 250 MG CAPSULA...,NaN,Genérico,NaN
6761,85534,729639,ACIDO URSODESOXICOLICO GRINDEKS 250 MG CAPSULA...,Grindeks As,20/11/2020,Anulado,24/03/2026,A05AA02,URSODEOXICOLICO ACIDO,False,...,Medicamento Sujeto A Prescripción Médica,NaN,False,False,729639,URSODEOXICOLICO ACIDO,ACIDO URSODESOXICOLICO GRINDEKS 250 MG CAPSULA...,NaN,Genérico,NaN

In [73]:
df_formulation[df_formulation["Cód. ATC"] == 'A05AA02']

,Nº Registro,Medicamento,Laboratorio,Fecha Aut.,Estado,Fecha Estado,Cód. ATC,Principios Activos,Nº P. Activos,¿Comercializado?,¿Triangulo Amarillo?,Observaciones,¿Sustituible?,¿Afecta conducción?,¿Problemas de suministro?
453,85534,ACIDO URSODESOXICOLICO GRINDEKS 250 MG CAPSULA...,Grindeks As,20/11/2020,Anulado,24/03/2026,A05AA02,URSODEOXICOLICO ACIDO,1,False,False,Medicamento Sujeto A Prescripción Médica,NaN,False,False
684,83490,ADISOCOL 150 MG COMPRIMIDOS EFG,Glenmark Arzneimittel Gmbh,04/10/2018,Autorizado,16/07/2020,A05AA02,URSODEOXICOLICO ACIDO,1,True,False,Medicamento Sujeto A Prescripción Médica,NaN,False,False
685,89783,ADISOCOL 250 MG CAPSULAS DURAS EFG,Glenmark Arzneimittel Gmbh,20/08/2024,Autorizado,21/08/2024,A05AA02,URSODEOXICOLICO ACIDO,1,False,False,Medicamento Sujeto A Prescripción Médica,NaN,False,False
686,83489,ADISOCOL 300 MG COMPRIMIDOS EFG,Glenmark Arzneimittel Gmbh,04/10/2018,Autorizado,16/07/2020,A05AA02,URSODEOXICOLICO ACIDO,1,True,False,Medicamento Sujeto A Prescripción Médica,NaN,False,True
687,83488,ADISOCOL 450 MG COMPRIMIDOS EFG,Glenmark Arzneimittel Gmbh,04/10/2018,Autorizado,16/07/2020,A05AA02,URSODEOXICOLICO ACIDO,1,True,False,Medicamento Sujeto A Prescripción Médica,NaN,False,True
688,89784,ADISOCOL 500 MG CAPSULAS DURAS EFG,Glenmark Arzneimittel Gmbh,21/08/2024,Autorizado,22/08/2024,A05AA02,URSODEOXICOLICO ACIDO,1,True,False,Medicamento Sujeto A Prescripción Médica,NaN,False,False
5978,91105,COLEFEL 500 MG COMPRIMIDOS RECUBIERTOS CON PEL...,Medinitaly Pharma Progress S.R.L.,19/03/2026,Autorizado,20/03/2026,A05AA02,URSODEOXICOLICO ACIDO,1,False,False,Medicamento Sujeto A Prescripción Médica,NaN,False,False
24605,56177,URSOBILANE 150 mg CAPSULAS,Laboratorio Estedi S.L.,01/05/1984,Autorizado,01/05/1984,A05AA02,URSODEOXICOLICO ACIDO,1,True,False,Medicamento Sujeto A Prescripción Médica,NaN,False,False
24606,65732,URSOBILANE 300 mg CAPSULAS,Laboratorio Estedi S.L.,20/10/2003,Autorizado,20/10/2003,A05AA02,URSODEOXICOLICO ACIDO,1,True,False,Medicamento Sujeto A Prescripción Médica,NaN,False,False
24607,75538,URSOBILANE 500 mg CAPSULAS,Laboratorio Estedi S.L.,28/02/2012,Autorizado,28/02/2012,A05AA02,URSODEOXICOLICO ACIDO,1,True,False,Medicamento Sujeto A Prescripción Médica,NaN,False,False
24608,56119,URSOCHOL 150 mg COMPRIMIDOS,Zambon S.A.U.,01/08/1983,Anulado,06/09/2021,A05AA02,URSODEOXICOLICO ACIDO,1,False,False,Medicamento Sujeto A Prescripción Médica,NaN,False,False