# Tasca S12.01. APIs REST

Descripció
Aplicaràs el que has après sobre APIs REST, mètodes HTTP i codis d'estat, utilitzant APIs públiques per consultar dades, filtrar-les i finalment desar-les en un DataFrame de pandas.

Recursos:
* Nivell 1:
{JSON} Placeholder [https://jsonplaceholder.typicode.com/]
* Nivell 2:
Try Public APIs for free [https://github.com/public-apis/public-apis]
* Nivell 3:
Open Data BCN [https://opendata-ajuntament.barcelona.cat/ca/desenvolupadors#APIS]

In [84]:
#Infrastructure
#!pip install requests
import pandas as pd
from pandas import json_normalize
import requests
import pprint

## Nivell 1

In [ ]:
# collect status codes for each query
status_codes = {}
# count number of records returned by each query
number_records = {}
# collect data to check the content
data = {}

Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.

Exploració bàsica amb una API de laboratori.
1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:

* Llista de publicacions (/posts)
* Llista d’usuaris (/users)
* Llista de tasques (/todos)

In [ ]:
r_get = requests.get('https://jsonplaceholder.typicode.com/')
#Checking status code of the GET and the content
print(f"Status code: {r_get.status_code}, \n{r_get.text}")

Status code: 200,

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="stylesheet" href="/style.css" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/prism-themes/1.9.0/prism-lucario.min.css"
    />
    <title>JSONPlaceholder - Free Fake REST API</title>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=G-E3C3GCQVBN"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || []
      function gtag() {
        dataLayer.push(arguments)
      }
      gtag('js', new Date())

      gtag('config', 'G-E3C3GCQVBN')
    </script>
    <script
      async
      src="https://media.ethicalads.io/media/client/ethicalads.min.js"
    ></script>
  </head>

  <body>
    <!-- Banner -->
    <div class="bg-blue-500 text-center py-2">
      <div class="container mx-auto">
        <a href="https://github.com/typicode/mistcss" class="text-white">Check my new project <strong>💧 MistCSS</strong> write React components with 50% less code</a>
      </div>
    </div>
    <header
      class="
        container
        mx-auto
        max-w-4xl
        flex flex-col
        md:flex-row
        justify-between
        py-one
        mb-three
      "
    >
      <h1>
        <a href="/" class="font-bold no-underline">JSONPlaceholder</a>
      </h1>
      <nav>
        <ul class="flex">
          <li><a href="/guide" class="mr-4 no-underline">Guide</a></li>
          <li>
            <a
              href="https://github.com/sponsors/typicode"
              class="mr-4 no-underline"
              >Sponsor this project</a
            >
          </li>
          <li>
            <a href="https://blog.typicode.com" class="mr-4 no-underline"
              >Blog</a
            >
          </li>
          <li>
            <a href="https://my-json-server.typicode.com" class="no-underline"
              >My JSON Server</a
            >
          </li>
        </ul>
      </nav>
    </header>

    <div>
<!-- Hero -->
<section id="hero" class="-mt-three py-20 mb-six -mx-2">
  <div class="container mx-auto max-w-4xl">
    <span class="text-6xl bold">{JSON} Placeholder</span>
    <h1 class="mt-two text-lg">
      Free fake and reliable API for testing and prototyping.
    </h1>
    <p class="mb-one text-lg">
      Powered by
      <a href="https://github.com/typicode/json-server">JSON Server</a>
      +
      <a href="https://github.com/typicode/lowdb">LowDB</a>.
    </p>
    <p><b>Serving ~3 billion requests each month</b>.</p>
  </div>
</section>

<!-- Sponsors -->
<section class="container mx-auto max-w-4xl mb-six">
  <h2 class="text-2xl mb-one">Sponsors</h2>
  <p class="mb-two">
    JSONPlaceholder is supported by the following companies and
    <a href="https://github.com/sponsors/typicode">Sponsors</a> on GitHub, check
    them out 💖
  </p>

  <p>
    <a href="https://mockend.com" target="_blank">
      <img src="mockend.svg" class="mb-two" style="height: 100px" />
    </a>
  </p>

  <p>
    <a href="https://zuplo.link/json-server-web" target="_blank">
      <img
        src="https://github.com/user-attachments/assets/adfee31f-a8b6-4684-9a9b-af4f03ac5b75"
        class="mb-two"
        style="height: 100px"
      />
    </a>
  </p>

  <p>
    <a
      href="http://git-tower.com/?utm_source=husky&utm_medium=referral"
      target="_blank"
    >
      <img
        src="./tower-icon-and-logo-1400x260.png"
        class="mb-two"
        style="height: 100px"
      />
    </a>
  </p>

  <p>
    <a href="https://serpapi.com/?utm_source=typicode" target="_blank">
      <img
        src="https://github.com/user-attachments/assets/52b3039d-1e4c-4c68-951c-93f0f1e73611"
        class="mb-two"
        style="height: 100px"
      />
    </a>
  </p>

  <p class="my-two">
    <a href="https://github.com/sponsors/typicode">Your company logo here</a>
  </p>
</section>

<!-- Example -->
<section class="container mx-auto max-w-4xl mb-four">
  <h2 class="text-2xl mb-one">Try it</h2>
  <p>Run this code here, in a console or from any site:</p>

  <pre><code id="example" class="language-javascript">fetch('https://jsonplaceholder.typicode.com/todos/1')
      .then(response => response.json())
      .then(json => console.log(json))</code></pre>

  <button
    id="run-button"
    class="bg-black hover:bg-gray-700 text-white font-bold py-quarter my-quarter px-4 rounded"
  >
    Run script
  </button>

  <pre><code id="result" class="language-javascript">{}</code></pre>
  <p id="run-message" class="invisible">
    Congrats! You've made your first call to JSONPlaceholder. 😃 🎉
  </p>
  <div
    class="horizontal flat adaptive"
    data-ea-publisher="jsonplaceholdertypicodecom"
    data-ea-style="stickybox"
    data-ea-keywords="javascript|typescript|mobile|react|vue|frontend|front-end|backend|back-end"
  ></div>
</section>
<main class="container mx-auto max-w-4xl"><h2>When to use</h2>
<p>JSONPlaceholder is a free online REST API that you can use <strong>whenever you need some fake data</strong>. It can be in a README on GitHub, for a demo on CodeSandbox, in code examples on Stack Overflow, ...or simply to test things locally.</p>
<h2>Resources</h2>
<p>JSONPlaceholder comes with a set of 6 common resources:</p>
<table>
<thead>
<tr>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/posts">/posts</a></td>
<td>100 posts</td>
</tr>
<tr>
<td><a href="/comments">/comments</a></td>
<td>500 comments</td>
</tr>
<tr>
<td><a href="/albums">/albums</a></td>
<td>100 albums</td>
</tr>
<tr>
<td><a href="/photos">/photos</a></td>
<td>5000 photos</td>
</tr>
<tr>
<td><a href="/todos">/todos</a></td>
<td>200 todos</td>
</tr>
<tr>
<td><a href="/users">/users</a></td>
<td>10 users</td>
</tr>
</tbody>
</table>
<p><strong>Note</strong>: resources have relations. For example: posts have many comments, albums have many photos, ... see <a href="/guide">guide</a> for the full list.</p>
<h2>Routes</h2>
<p>All HTTP methods are supported. You can use http or https for your requests.</p>
<table>
<thead>
<tr>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td>GET</td>
<td><a href="/posts">/posts</a></td>
</tr>
<tr>
<td>GET</td>
<td><a href="/posts/1">/posts/1</a></td>
</tr>
<tr>
<td>GET</td>
<td><a href="/posts/1/comments">/posts/1/comments</a></td>
</tr>
<tr>
<td>GET</td>
<td><a href="/comments?postId=1">/comments?postId=1</a></td>
</tr>
<tr>
<td>POST</td>
<td>/posts</td>
</tr>
<tr>
<td>PUT</td>
<td>/posts/1</td>
</tr>
<tr>
<td>PATCH</td>
<td>/posts/1</td>
</tr>
<tr>
<td>DELETE</td>
<td>/posts/1</td>
</tr>
</tbody>
</table>
<p><strong>Note</strong>: see <a href="/guide">guide</a> for usage examples.</p>
<h2>Use your own data</h2>
<p>With our sponsor <a href="https://mockend.com">Mockend</a> and a simple GitHub repo, you can have your own fake online REST server in seconds.</p>
</main>

<script>
  // Use http or https based on location.protocol
  var example = document.getElementById("example");
  example.textContent = example.textContent.replace("http:", location.protocol);

  // Highlight result element
  var result = document.getElementById("result");

  // Run example
  var runButton = document.getElementById("run-button");
  runButton.onclick = function () {
    var root = location.protocol + "//jsonplaceholder.typicode.com";
    var runMessage = document.getElementById("run-message");

    fetch("https://jsonplaceholder.typicode.com/todos/1")
      .then((response) => response.json())
      .then((json) => {
        var str = JSON.stringify(json, null, "  ");

        // Format result
        result.innerHTML = Prism.highlight(
          str,
          Prism.languages.javascript,
          "javascript",
        );

        runMessage.className = "";
      });
  };
</script>
</div>

    <!-- Footer -->
    <footer class="container mx-auto max-w-4xl mt-four">
      <div class="mb-one">
        <a href="https://github.com/users/typicode/sponsorship">
          <strong>You can sponsor this project (and others) on GitHub</strong>
        </a>
      </div>
      <div class="mb-one">
        Coded and maintained with ❤️ by
        <a href="https://github.com/typicode">typicode</a> © 2024
      </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"></script>
  </body>
</html>

In [ ]:
# /POSTS request
r_post = requests.get('https://jsonplaceholder.typicode.com/posts/')
status_codes['posts'] = r_post.status_code
r_post_data = r_post.json()
data['posts'] = r_post_data
number_records['posts'] = len(r_post_data)
pprint.pprint(r_post_data)

[{'body': 'quia et suscipit\n'
          'suscipit recusandae consequuntur expedita et cum\n'
          'reprehenderit molestiae ut ut quas totam\n'
          'nostrum rerum est autem sunt rem eveniet architecto',
  'id': 1,
  'title': 'sunt aut facere repellat provident occaecati excepturi optio '
           'reprehenderit',
  'userId': 1},
 {'body': 'est rerum tempore vitae\n'
          'sequi sint nihil reprehenderit dolor beatae ea dolores neque\n'
          'fugiat blanditiis voluptate porro vel nihil molestiae ut '
          'reiciendis\n'
          'qui aperiam non debitis possimus qui neque nisi nulla',
  'id': 2,
  'title': 'qui est esse',
  'userId': 1},
 {'body': 'et iusto sed quo iure\n'
          'voluptatem occaecati omnis eligendi aut ad\n'
          'voluptatem doloribus vel accusantium quis pariatur\n'
          'molestiae porro eius odio et labore et velit aut',
  'id': 3,
  'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
  'userId': 1},
 {'body': 'ullam et saepe reiciendis voluptatem adipisci\n'
          'sit amet autem assumenda provident rerum culpa\n'
          'quis hic commodi nesciunt rem tenetur doloremque ipsam iure\n'
          'quis sunt voluptatem rerum illo velit',
  'id': 4,
  'title': 'eum et est occaecati',
  'userId': 1},
 {'body': 'repudiandae veniam quaerat sunt sed\n'
          'alias aut fugiat sit autem sed est\n'
          'voluptatem omnis possimus esse voluptatibus quis\n'
          'est aut tenetur dolor neque',
  'id': 5,
  'title': 'nesciunt quas odio',
  'userId': 1},
 {'body': 'ut aspernatur corporis harum nihil quis provident sequi\n'
          'mollitia nobis aliquid molestiae\n'
          'perspiciatis et ea nemo ab reprehenderit accusantium quas\n'
          'voluptate dolores velit et doloremque molestiae',
  'id': 6,
  'title': 'dolorem eum magni eos aperiam quia',
  'userId': 1},
 {'body': 'dolore placeat quibusdam ea quo vitae\n'
          'magni quis enim qui quis quo nemo aut saepe\n'
          'quidem repellat excepturi ut quia\n'
          'sunt ut sequi eos ea sed quas',
  'id': 7,
  'title': 'magnam facilis autem',
  'userId': 1},
 {'body': 'dignissimos aperiam dolorem qui eum\n'
          'facilis quibusdam animi sint suscipit qui sint possimus cum\n'
          'quaerat magni maiores excepturi\n'
          'ipsam ut commodi dolor voluptatum modi aut vitae',
  'id': 8,
  'title': 'dolorem dolore est ipsam',
  'userId': 1},
 {'body': 'consectetur animi nesciunt iure dolore\n'
          'enim quia ad\n'
          'veniam autem ut quam aut nobis\n'
          'et est aut quod aut provident voluptas autem voluptas',
  'id': 9,
  'title': 'nesciunt iure omnis dolorem tempora et accusantium',
  'userId': 1},
 {'body': 'quo et expedita modi cum officia vel magni\n'
          'doloribus qui repudiandae\n'
          'vero nisi sit\n'
          'quos veniam quod sed accusamus veritatis error',
  'id': 10,
  'title': 'optio molestias id quia eum',
  'userId': 1},
 {'body': 'delectus reiciendis molestiae occaecati non minima eveniet qui '
          'voluptatibus\n'
          'accusamus in eum beatae sit\n'
          'vel qui neque voluptates ut commodi qui incidunt\n'
          'ut animi commodi',
  'id': 11,
  'title': 'et ea vero quia laudantium autem',
  'userId': 2},
 {'body': 'itaque id aut magnam\n'
          'praesentium quia et ea odit et ea voluptas et\n'
          'sapiente quia nihil amet occaecati quia id voluptatem\n'
          'incidunt ea est distinctio odio',
  'id': 12,
  'title': 'in quibusdam tempore odit est dolorem',
  'userId': 2},
 {'body': 'aut dicta possimus sint mollitia voluptas commodi quo doloremque\n'
          'iste corrupti reiciendis voluptatem eius rerum\n'
          'sit cumque quod eligendi laborum minima\n'
          'perferendis recusandae assumenda consectetur porro architecto ipsum '
          'ipsam',
  'id': 13,
  'title': 'dolorum ut in voluptas mollitia et saepe quo animi',
  'userId': 2},
 {'body': 'fuga et accusamus dolorum perferendis illo voluptas\n'
          'non doloremque neque facere\n'
          'ad qui dolorum molestiae beatae\n'
          'sed aut voluptas totam sit illum',
  'id': 14,
  'title': 'voluptatem eligendi optio',
  'userId': 2},
 {'body': 'reprehenderit quos placeat\n'
          'velit minima officia dolores impedit repudiandae molestiae nam\n'
          'voluptas recusandae quis delectus\n'
          'officiis harum fugiat vitae',
  'id': 15,
  'title': 'eveniet quod temporibus',
  'userId': 2},
 {'body': 'suscipit nam nisi quo aperiam aut\n'
          'asperiores eos fugit maiores voluptatibus quia\n'
          'voluptatem quis ullam qui in alias quia est\n'
          'consequatur magni mollitia accusamus ea nisi voluptate dicta',
  'id': 16,
  'title': 'sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam '
           'odio',
  'userId': 2},
 {'body': 'eos voluptas et aut odit natus earum\n'
          'aspernatur fuga molestiae ullam\n'
          'deserunt ratione qui eos\n'
          'qui nihil ratione nemo velit ut aut id quo',
  'id': 17,
  'title': 'fugit voluptas sed molestias voluptatem provident',
  'userId': 2},
 {'body': 'eveniet quo quis\n'
          'laborum totam consequatur non dolor\n'
          'ut et est repudiandae\n'
          'est voluptatem vel debitis et magnam',
  'id': 18,
  'title': 'voluptate et itaque vero tempora molestiae',
  'userId': 2},
 {'body': 'illum quis cupiditate provident sit magnam\n'
          'ea sed aut omnis\n'
          'veniam maiores ullam consequatur atque\n'
          'adipisci quo iste expedita sit quos voluptas',
  'id': 19,
  'title': 'adipisci placeat illum aut reiciendis qui',
  'userId': 2},
 {'body': 'qui consequuntur ducimus possimus quisquam amet similique\n'
          'suscipit porro ipsam amet\n'
          'eos veritatis officiis exercitationem vel fugit aut necessitatibus '
          'totam\n'
          'omnis rerum consequatur expedita quidem cumque explicabo',
  'id': 20,
  'title': 'doloribus ad provident suscipit at',
  'userId': 2},
 {'body': 'repellat aliquid praesentium dolorem quo\n'
          'sed totam minus non itaque\n'
          'nihil labore molestiae sunt dolor eveniet hic recusandae veniam\n'
          'tempora et tenetur expedita sunt',
  'id': 21,
  'title': 'asperiores ea ipsam voluptatibus modi minima quia sint',
  'userId': 3},
 {'body': 'eos qui et ipsum ipsam suscipit aut\n'
          'sed omnis non odio\n'
          'expedita earum mollitia molestiae aut atque rem suscipit\n'
          'nam impedit esse',
  'id': 22,
  'title': 'dolor sint quo a velit explicabo quia nam',
  'userId': 3},
 {'body': 'veritatis unde neque eligendi\n'
          'quae quod architecto quo neque vitae\n'
          'est illo sit tempora doloremque fugit quod\n'
          'et et vel beatae sequi ullam sed tenetur perspiciatis',
  'id': 23,
  'title': 'maxime id vitae nihil numquam',
  'userId': 3},
 {'body': 'enim et ex nulla\n'
          'omnis voluptas quia qui\n'
          'voluptatem consequatur numquam aliquam sunt\n'
          'totam recusandae id dignissimos aut sed asperiores deserunt',
  'id': 24,
  'title': 'autem hic labore sunt dolores incidunt',
  'userId': 3},
 {'body': 'ullam consequatur ut\n'
          'omnis quis sit vel consequuntur\n'
          'ipsa eligendi ipsum molestiae et omnis error nostrum\n'
          'molestiae illo tempore quia et distinctio',
  'id': 25,
  'title': 'rem alias distinctio quo quis',
  'userId': 3},
 {'body': 'similique esse doloribus nihil accusamus\n'
          'omnis dolorem fuga consequuntur reprehenderit fugit recusandae '
          'temporibus\n'
          'perspiciatis cum ut laudantium\n'
          'omnis aut molestiae vel vero',
  'id': 26,
  'title': 'est et quae odit qui non',
  'userId': 3},
 {'body': 'eum sed dolores ipsam sint possimus debitis occaecati\n'
          'debitis qui qui et\n'
          'ut placeat enim earum aut odit facilis\n'
          'consequatur suscipit necessitatibus rerum sed inventore temporibus '
          'consequatur',
  'id': 27,
  'title': 'quasi id et eos tenetur aut quo autem',
  'userId': 3},
 {'body': 'non et quaerat ex quae ad maiores\n'
          'maiores recusandae totam aut blanditiis mollitia quas illo\n'
          'ut voluptatibus voluptatem\n'
          'similique nostrum eum',
  'id': 28,
  'title': 'delectus ullam et corporis nulla voluptas sequi',
  'userId': 3},
 {'body': 'odit magnam ut saepe sed non qui\n'
          'tempora atque nihil\n'
          'accusamus illum doloribus illo dolor\n'
          'eligendi repudiandae odit magni similique sed cum maiores',
  'id': 29,
  'title': 'iusto eius quod necessitatibus culpa ea',
  'userId': 3},
 {'body': 'alias dolor cumque\n'
          'impedit blanditiis non eveniet odio maxime\n'
          'blanditiis amet eius quis tempora quia autem rem\n'
          'a provident perspiciatis quia',
  'id': 30,
  'title': 'a quo magni similique perferendis',
  'userId': 3},
 {'body': 'debitis eius sed quibusdam non quis consectetur vitae\n'
          'impedit ut qui consequatur sed aut in\n'
          'quidem sit nostrum et maiores adipisci atque\n'
          'quaerat voluptatem adipisci repudiandae',
  'id': 31,
  'title': 'ullam ut quidem id aut vel consequuntur',
  'userId': 4},
 {'body': 'deserunt eos nobis asperiores et hic\n'
          'est debitis repellat molestiae optio\n'
          'nihil ratione ut eos beatae quibusdam distinctio maiores\n'
          'earum voluptates et aut adipisci ea maiores voluptas maxime',
  'id': 32,
  'title': 'doloremque illum aliquid sunt',
  'userId': 4},
 {'body': 'rerum ut et numquam laborum odit est sit\n'
          'id qui sint in\n'
          'quasi tenetur tempore aperiam et quaerat qui in\n'
          'rerum officiis sequi cumque quod',
  'id': 33,
  'title': 'qui explicabo molestiae dolorem',
  'userId': 4},
 {'body': 'ea velit perferendis earum ut voluptatem voluptate itaque iusto\n'
          'totam pariatur in\n'
          'nemo voluptatem voluptatem autem magni tempora minima in\n'
          'est distinctio qui assumenda accusamus dignissimos officia nesciunt '
          'nobis',
  'id': 34,
  'title': 'magnam ut rerum iure',
  'userId': 4},
 {'body': 'nisi error delectus possimus ut eligendi vitae\n'
          'placeat eos harum cupiditate facilis reprehenderit voluptatem '
          'beatae\n'
          'modi ducimus quo illum voluptas eligendi\n'
          'et nobis quia fugit',
  'id': 35,
  'title': 'id nihil consequatur molestias animi provident',
  'userId': 4},
 {'body': 'ad mollitia et omnis minus architecto odit\n'
          'voluptas doloremque maxime aut non ipsa qui alias veniam\n'
          'blanditiis culpa aut quia nihil cumque facere et occaecati\n'
          'qui aspernatur quia eaque ut aperiam inventore',
  'id': 36,
  'title': 'fuga nam accusamus voluptas reiciendis itaque',
  'userId': 4},
 {'body': 'debitis et eaque non officia sed nesciunt pariatur vel\n'
          'voluptatem iste vero et ea\n'
          'numquam aut expedita ipsum nulla in\n'
          'voluptates omnis consequatur aut enim officiis in quam qui',
  'id': 37,
  'title': 'provident vel ut sit ratione est',
  'userId': 4},
 {'body': 'animi esse sit aut sit nesciunt assumenda eum voluptas\n'
          'quia voluptatibus provident quia necessitatibus ea\n'
          'rerum repudiandae quia voluptatem delectus fugit aut id quia\n'
          'ratione optio eos iusto veniam iure',
  'id': 38,
  'title': 'explicabo et eos deleniti nostrum ab id repellendus',
  'userId': 4},
 {'body': 'corporis rerum ducimus vel eum accusantium\n'
          'maxime aspernatur a porro possimus iste omnis\n'
          'est in deleniti asperiores fuga aut\n'
          'voluptas sapiente vel dolore minus voluptatem incidunt ex',
  'id': 39,
  'title': 'eos dolorem iste accusantium est eaque quam',
  'userId': 4},
 {'body': 'ut voluptatum aliquid illo tenetur nemo sequi quo facilis\n'
          'ipsum rem optio mollitia quas\n'
          'voluptatem eum voluptas qui\n'
          'unde omnis voluptatem iure quasi maxime voluptas nam',
  'id': 40,
  'title': 'enim quo cumque',
  'userId': 4},
 {'body': 'molestias id nostrum\n'
          'excepturi molestiae dolore omnis repellendus quaerat saepe\n'
          'consectetur iste quaerat tenetur asperiores accusamus ex ut\n'
          'nam quidem est ducimus sunt debitis saepe',
  'id': 41,
  'title': 'non est facere',
  'userId': 5},
 {'body': 'odio fugit voluptatum ducimus earum autem est incidunt voluptatem\n'
          'odit reiciendis aliquam sunt sequi nulla dolorem\n'
          'non facere repellendus voluptates quia\n'
          'ratione harum vitae ut',
  'id': 42,
  'title': 'commodi ullam sint et excepturi error explicabo praesentium '
           'voluptas',
  'userId': 5},
 {'body': 'similique fugit est\n'
          'illum et dolorum harum et voluptate eaque quidem\n'
          'exercitationem quos nam commodi possimus cum odio nihil nulla\n'
          'dolorum exercitationem magnam ex et a et distinctio debitis',
  'id': 43,
  'title': 'eligendi iste nostrum consequuntur adipisci praesentium sit beatae '
           'perferendis',
  'userId': 5},
 {'body': 'temporibus est consectetur dolore\n'
          'et libero debitis vel velit laboriosam quia\n'
          'ipsum quibusdam qui itaque fuga rem aut\n'
          'ea et iure quam sed maxime ut distinctio quae',
  'id': 44,
  'title': 'optio dolor molestias sit',
  'userId': 5},
 {'body': 'est natus reiciendis nihil possimus aut provident\n'
          'ex et dolor\n'
          'repellat pariatur est\n'
          'nobis rerum repellendus dolorem autem',
  'id': 45,
  'title': 'ut numquam possimus omnis eius suscipit laudantium iure',
  'userId': 5},
 {'body': 'voluptatem quisquam iste\n'
          'voluptatibus natus officiis facilis dolorem\n'
          'quis quas ipsam\n'
          'vel et voluptatum in aliquid',
  'id': 46,
  'title': 'aut quo modi neque nostrum ducimus',
  'userId': 5},
 {'body': 'voluptatem assumenda ut qui ut cupiditate aut impedit veniam\n'
          'occaecati nemo illum voluptatem laudantium\n'
          'molestiae beatae rerum ea iure soluta nostrum\n'
          'eligendi et voluptate',
  'id': 47,
  'title': 'quibusdam cumque rem aut deserunt',
  'userId': 5},
 {'body': 'voluptates quo voluptatem facilis iure occaecati\n'
          'vel assumenda rerum officia et\n'
          'illum perspiciatis ab deleniti\n'
          'laudantium repellat ad ut et autem reprehenderit',
  'id': 48,
  'title': 'ut voluptatem illum ea doloribus itaque eos',
  'userId': 5},
 {'body': 'inventore ab sint\n'
          'natus fugit id nulla sequi architecto nihil quaerat\n'
          'eos tenetur in in eum veritatis non\n'
          'quibusdam officiis aspernatur cumque aut commodi aut',
  'id': 49,
  'title': 'laborum non sunt aut ut assumenda perspiciatis voluptas',
  'userId': 5},
 {'body': 'error suscipit maxime adipisci consequuntur recusandae\n'
          'voluptas eligendi et est et voluptates\n'
          'quia distinctio ab amet quaerat molestiae et vitae\n'
          'adipisci impedit sequi nesciunt quis consectetur',
  'id': 50,
  'title': 'repellendus qui recusandae incidunt voluptates tenetur qui omnis '
           'exercitationem',
  'userId': 5},
 {'body': 'sunt dolores aut doloribus\n'
          'dolore doloribus voluptates tempora et\n'
          'doloremque et quo\n'
          'cum asperiores sit consectetur dolorem',
  'id': 51,
  'title': 'soluta aliquam aperiam consequatur illo quis voluptas',
  'userId': 6},
 {'body': 'iusto est quibusdam fuga quas quaerat molestias\n'
          'a enim ut sit accusamus enim\n'
          'temporibus iusto accusantium provident architecto\n'
          'soluta esse reprehenderit qui laborum',
  'id': 52,
  'title': 'qui enim et consequuntur quia animi quis voluptate quibusdam',
  'userId': 6},
 {'body': 'minima harum praesentium eum rerum illo dolore\n'
          'quasi exercitationem rerum nam\n'
          'porro quis neque quo\n'
          'consequatur minus dolor quidem veritatis sunt non explicabo '
          'similique',
  'id': 53,
  'title': 'ut quo aut ducimus alias',
  'userId': 6},
 {'body': 'totam corporis dignissimos\n'
          'vitae dolorem ut occaecati accusamus\n'
          'ex velit deserunt\n'
          'et exercitationem vero incidunt corrupti mollitia',
  'id': 54,
  'title': 'sit asperiores ipsam eveniet odio non quia',
  'userId': 6},
 {'body': 'debitis excepturi ea perferendis harum libero optio\n'
          'eos accusamus cum fuga ut sapiente repudiandae\n'
          'et ut incidunt omnis molestiae\n'
          'nihil ut eum odit',
  'id': 55,
  'title': 'sit vel voluptatem et non libero',
  'userId': 6},
 {'body': 'aut est omnis dolores\n'
          'neque rerum quod ea rerum velit pariatur beatae excepturi\n'
          'et provident voluptas corrupti\n'
          'corporis harum reprehenderit dolores eligendi',
  'id': 56,
  'title': 'qui et at rerum necessitatibus',
  'userId': 6},
 {'body': 'at pariatur consequuntur earum quidem\n'
          'quo est laudantium soluta voluptatem\n'
          'qui ullam et est\n'
          'et cum voluptas voluptatum repellat est',
  'id': 57,
  'title': 'sed ab est est',
  'userId': 6},
 {'body': 'veniam voluptatum quae adipisci id\n'
          'et id quia eos ad et dolorem\n'
          'aliquam quo nisi sunt eos impedit error\n'
          'ad similique veniam',
  'id': 58,
  'title': 'voluptatum itaque dolores nisi et quasi',
  'userId': 6},
 {'body': 'perspiciatis et quam ea autem temporibus non voluptatibus qui\n'
          'beatae a earum officia nesciunt dolores suscipit voluptas et\n'
          'animi doloribus cum rerum quas et magni\n'
          'et hic ut ut commodi expedita sunt',
  'id': 59,
  'title': 'qui commodi dolor at maiores et quis id accusantium',
  'userId': 6},
 {'body': 'asperiores sunt ab assumenda cumque modi velit\n'
          'qui esse omnis\n'
          'voluptate et fuga perferendis voluptas\n'
          'illo ratione amet aut et omnis',
  'id': 60,
  'title': 'consequatur placeat omnis quisquam quia reprehenderit fugit '
           'veritatis facere',
  'userId': 6},
 {'body': 'ab nemo optio odio\n'
          'delectus tenetur corporis similique nobis repellendus rerum omnis '
          'facilis\n'
          'vero blanditiis debitis in nesciunt doloribus dicta dolores\n'
          'magnam minus velit',
  'id': 61,
  'title': 'voluptatem doloribus consectetur est ut ducimus',
  'userId': 7},
 {'body': 'enim aspernatur illo distinctio quae praesentium\n'
          'beatae alias amet delectus qui voluptate distinctio\n'
          'odit sint accusantium autem omnis\n'
          'quo molestiae omnis ea eveniet optio',
  'id': 62,
  'title': 'beatae enim quia vel',
  'userId': 7},
 {'body': 'enim adipisci aspernatur nemo\n'
          'numquam omnis facere dolorem dolor ex quis temporibus incidunt\n'
          'ab delectus culpa quo reprehenderit blanditiis asperiores\n'
          'accusantium ut quam in voluptatibus voluptas ipsam dicta',
  'id': 63,
  'title': 'voluptas blanditiis repellendus animi ducimus error sapiente et '
           'suscipit',
  'userId': 7},
 {'body': 'id velit blanditiis\n'
          'eum ea voluptatem\n'
          'molestiae sint occaecati est eos perspiciatis\n'
          'incidunt a error provident eaque aut aut qui',
  'id': 64,
  'title': 'et fugit quas eum in in aperiam quod',
  'userId': 7},
 {'body': 'voluptatibus ex esse\n'
          'sint explicabo est aliquid cumque adipisci fuga repellat labore\n'
          'molestiae corrupti ex saepe at asperiores et perferendis\n'
          'natus id esse incidunt pariatur',
  'id': 65,
  'title': 'consequatur id enim sunt et et',
  'userId': 7},
 {'body': 'officia veritatis tenetur vero qui itaque\n'
          'sint non ratione\n'
          'sed et ut asperiores iusto eos molestiae nostrum\n'

In [ ]:
# /USERS request
r_users = requests.get('https://jsonplaceholder.typicode.com/users/')
status_codes['users'] = r_users.status_code
r_users_data = r_users.json()
data['users'] = r_users_data
number_records['users'] = len(r_users_data)
pprint.pprint(r_users_data)

[{'address': {'city': 'Gwenborough',
              'geo': {'lat': '-37.3159', 'lng': '81.1496'},
              'street': 'Kulas Light',
              'suite': 'Apt. 556',
              'zipcode': '92998-3874'},
  'company': {'bs': 'harness real-time e-markets',
              'catchPhrase': 'Multi-layered client-server neural-net',
              'name': 'Romaguera-Crona'},
  'email': 'Sincere@april.biz',
  'id': 1,
  'name': 'Leanne Graham',
  'phone': '1-770-736-8031 x56442',
  'username': 'Bret',
  'website': 'hildegard.org'},
 {'address': {'city': 'Wisokyburgh',
              'geo': {'lat': '-43.9509', 'lng': '-34.4618'},
              'street': 'Victor Plains',
              'suite': 'Suite 879',
              'zipcode': '90566-7771'},
  'company': {'bs': 'synergize scalable supply-chains',
              'catchPhrase': 'Proactive didactic contingency',
              'name': 'Deckow-Crist'},
  'email': 'Shanna@melissa.tv',
  'id': 2,
  'name': 'Ervin Howell',
  'phone': '010-692-6593 x09125',
  'username': 'Antonette',
  'website': 'anastasia.net'},
 {'address': {'city': 'McKenziehaven',
              'geo': {'lat': '-68.6102', 'lng': '-47.0653'},
              'street': 'Douglas Extension',
              'suite': 'Suite 847',
              'zipcode': '59590-4157'},
  'company': {'bs': 'e-enable strategic applications',
              'catchPhrase': 'Face to face bifurcated interface',
              'name': 'Romaguera-Jacobson'},
  'email': 'Nathan@yesenia.net',
  'id': 3,
  'name': 'Clementine Bauch',
  'phone': '1-463-123-4447',
  'username': 'Samantha',
  'website': 'ramiro.info'},
 {'address': {'city': 'South Elvis',
              'geo': {'lat': '29.4572', 'lng': '-164.2990'},
              'street': 'Hoeger Mall',
              'suite': 'Apt. 692',
              'zipcode': '53919-4257'},
  'company': {'bs': 'transition cutting-edge web services',
              'catchPhrase': 'Multi-tiered zero tolerance productivity',
              'name': 'Robel-Corkery'},
  'email': 'Julianne.OConner@kory.org',
  'id': 4,
  'name': 'Patricia Lebsack',
  'phone': '493-170-9623 x156',
  'username': 'Karianne',
  'website': 'kale.biz'},
 {'address': {'city': 'Roscoeview',
              'geo': {'lat': '-31.8129', 'lng': '62.5342'},
              'street': 'Skiles Walks',
              'suite': 'Suite 351',
              'zipcode': '33263'},
  'company': {'bs': 'revolutionize end-to-end systems',
              'catchPhrase': 'User-centric fault-tolerant solution',
              'name': 'Keebler LLC'},
  'email': 'Lucio_Hettinger@annie.ca',
  'id': 5,
  'name': 'Chelsey Dietrich',
  'phone': '(254)954-1289',
  'username': 'Kamren',
  'website': 'demarco.info'},
 {'address': {'city': 'South Christy',
              'geo': {'lat': '-71.4197', 'lng': '71.7478'},
              'street': 'Norberto Crossing',
              'suite': 'Apt. 950',
              'zipcode': '23505-1337'},
  'company': {'bs': 'e-enable innovative applications',
              'catchPhrase': 'Synchronised bottom-line interface',
              'name': 'Considine-Lockman'},
  'email': 'Karley_Dach@jasper.info',
  'id': 6,
  'name': 'Mrs. Dennis Schulist',
  'phone': '1-477-935-8478 x6430',
  'username': 'Leopoldo_Corkery',
  'website': 'ola.org'},
 {'address': {'city': 'Howemouth',
              'geo': {'lat': '24.8918', 'lng': '21.8984'},
              'street': 'Rex Trail',
              'suite': 'Suite 280',
              'zipcode': '58804-1099'},
  'company': {'bs': 'generate enterprise e-tailers',
              'catchPhrase': 'Configurable multimedia task-force',
              'name': 'Johns Group'},
  'email': 'Telly.Hoeger@billy.biz',
  'id': 7,
  'name': 'Kurtis Weissnat',
  'phone': '210.067.6132',
  'username': 'Elwyn.Skiles',
  'website': 'elvis.io'},
 {'address': {'city': 'Aliyaview',
              'geo': {'lat': '-14.3990', 'lng': '-120.7677'},
              'street': 'Ellsworth Summit',
              'suite': 'Suite 729',
              'zipcode': '45169'},
  'company': {'bs': 'e-enable extensible e-tailers',
              'catchPhrase': 'Implemented secondary concept',
              'name': 'Abernathy Group'},
  'email': 'Sherwood@rosamond.me',
  'id': 8,
  'name': 'Nicholas Runolfsdottir V',
  'phone': '586.493.6943 x140',
  'username': 'Maxime_Nienow',
  'website': 'jacynthe.com'},
 {'address': {'city': 'Bartholomebury',
              'geo': {'lat': '24.6463', 'lng': '-168.8889'},
              'street': 'Dayna Park',
              'suite': 'Suite 449',
              'zipcode': '76495-3109'},
  'company': {'bs': 'aggregate real-time technologies',
              'catchPhrase': 'Switchable contextually-based project',
              'name': 'Yost and Sons'},
  'email': 'Chaim_McDermott@dana.io',
  'id': 9,
  'name': 'Glenna Reichert',
  'phone': '(775)976-6794 x41206',
  'username': 'Delphine',
  'website': 'conrad.com'},
 {'address': {'city': 'Lebsackbury',
              'geo': {'lat': '-38.2386', 'lng': '57.2232'},
              'street': 'Kattie Turnpike',
              'suite': 'Suite 198',
              'zipcode': '31428-2261'},
  'company': {'bs': 'target end-to-end models',
              'catchPhrase': 'Centralized empowering task-force',
              'name': 'Hoeger LLC'},
  'email': 'Rey.Padberg@karina.biz',
  'id': 10,
  'name': 'Clementina DuBuque',
  'phone': '024-648-3804',
  'username': 'Moriah.Stanton',
  'website': 'ambrose.net'}]

In [ ]:
# /TODOS request
r_todos = requests.get('https://jsonplaceholder.typicode.com/todos/')
status_codes['todos'] = r_todos.status_code
r_todos_data = r_todos.json()
data['todos'] = r_todos_data
number_records['todos'] = len(r_todos_data)
pprint.pprint(r_todos_data)

[{'completed': False, 'id': 1, 'title': 'delectus aut autem', 'userId': 1},
 {'completed': False,
  'id': 2,
  'title': 'quis ut nam facilis et officia qui',
  'userId': 1},
 {'completed': False, 'id': 3, 'title': 'fugiat veniam minus', 'userId': 1},
 {'completed': True, 'id': 4, 'title': 'et porro tempora', 'userId': 1},
 {'completed': False,
  'id': 5,
  'title': 'laboriosam mollitia et enim quasi adipisci quia provident illum',
  'userId': 1},
 {'completed': False,
  'id': 6,
  'title': 'qui ullam ratione quibusdam voluptatem quia omnis',
  'userId': 1},
 {'completed': False,
  'id': 7,
  'title': 'illo expedita consequatur quia in',
  'userId': 1},
 {'completed': True,
  'id': 8,
  'title': 'quo adipisci enim quam ut ab',
  'userId': 1},
 {'completed': False,
  'id': 9,
  'title': 'molestiae perspiciatis ipsa',
  'userId': 1},
 {'completed': True,
  'id': 10,
  'title': 'illo est ratione doloremque quia maiores aut',
  'userId': 1},
 {'completed': True,
  'id': 11,
  'title': 'vero rerum temporibus dolor',
  'userId': 1},
 {'completed': True,
  'id': 12,
  'title': 'ipsa repellendus fugit nisi',
  'userId': 1},
 {'completed': False, 'id': 13, 'title': 'et doloremque nulla', 'userId': 1},
 {'completed': True,
  'id': 14,
  'title': 'repellendus sunt dolores architecto voluptatum',
  'userId': 1},
 {'completed': True,
  'id': 15,
  'title': 'ab voluptatum amet voluptas',
  'userId': 1},
 {'completed': True,
  'id': 16,
  'title': 'accusamus eos facilis sint et aut voluptatem',
  'userId': 1},
 {'completed': True,
  'id': 17,
  'title': 'quo laboriosam deleniti aut qui',
  'userId': 1},
 {'completed': False,
  'id': 18,
  'title': 'dolorum est consequatur ea mollitia in culpa',
  'userId': 1},
 {'completed': True,
  'id': 19,
  'title': 'molestiae ipsa aut voluptatibus pariatur dolor nihil',
  'userId': 1},
 {'completed': True,
  'id': 20,
  'title': 'ullam nobis libero sapiente ad optio sint',
  'userId': 1},
 {'completed': False,
  'id': 21,
  'title': 'suscipit repellat esse quibusdam voluptatem incidunt',
  'userId': 2},
 {'completed': True,
  'id': 22,
  'title': 'distinctio vitae autem nihil ut molestias quo',
  'userId': 2},
 {'completed': False,
  'id': 23,
  'title': 'et itaque necessitatibus maxime molestiae qui quas velit',
  'userId': 2},
 {'completed': False,
  'id': 24,
  'title': 'adipisci non ad dicta qui amet quaerat doloribus ea',
  'userId': 2},
 {'completed': True,
  'id': 25,
  'title': 'voluptas quo tenetur perspiciatis explicabo natus',
  'userId': 2},
 {'completed': True, 'id': 26, 'title': 'aliquam aut quasi', 'userId': 2},
 {'completed': True,
  'id': 27,
  'title': 'veritatis pariatur delectus',
  'userId': 2},
 {'completed': False,
  'id': 28,
  'title': 'nesciunt totam sit blanditiis sit',
  'userId': 2},
 {'completed': False, 'id': 29, 'title': 'laborum aut in quam', 'userId': 2},
 {'completed': True,
  'id': 30,
  'title': 'nemo perspiciatis repellat ut dolor libero commodi blanditiis '
           'omnis',
  'userId': 2},
 {'completed': False,
  'id': 31,
  'title': 'repudiandae totam in est sint facere fuga',
  'userId': 2},
 {'completed': False,
  'id': 32,
  'title': 'earum doloribus ea doloremque quis',
  'userId': 2},
 {'completed': False, 'id': 33, 'title': 'sint sit aut vero', 'userId': 2},
 {'completed': False,
  'id': 34,
  'title': 'porro aut necessitatibus eaque distinctio',
  'userId': 2},
 {'completed': True,
  'id': 35,
  'title': 'repellendus veritatis molestias dicta incidunt',
  'userId': 2},
 {'completed': True,
  'id': 36,
  'title': 'excepturi deleniti adipisci voluptatem et neque optio illum ad',
  'userId': 2},
 {'completed': False, 'id': 37, 'title': 'sunt cum tempora', 'userId': 2},
 {'completed': False, 'id': 38, 'title': 'totam quia non', 'userId': 2},
 {'completed': False,
  'id': 39,
  'title': 'doloremque quibusdam asperiores libero corrupti illum qui omnis',
  'userId': 2},
 {'completed': True,
  'id': 40,
  'title': 'totam atque quo nesciunt',
  'userId': 2},
 {'completed': False,
  'id': 41,
  'title': 'aliquid amet impedit consequatur aspernatur placeat eaque fugiat '
           'suscipit',
  'userId': 3},
 {'completed': False,
  'id': 42,
  'title': 'rerum perferendis error quia ut eveniet',
  'userId': 3},
 {'completed': True,
  'id': 43,
  'title': 'tempore ut sint quis recusandae',
  'userId': 3},
 {'completed': True,
  'id': 44,
  'title': 'cum debitis quis accusamus doloremque ipsa natus sapiente omnis',
  'userId': 3},
 {'completed': False,
  'id': 45,
  'title': 'velit soluta adipisci molestias reiciendis harum',
  'userId': 3},
 {'completed': False,
  'id': 46,
  'title': 'vel voluptatem repellat nihil placeat corporis',
  'userId': 3},
 {'completed': False,
  'id': 47,
  'title': 'nam qui rerum fugiat accusamus',
  'userId': 3},
 {'completed': False,
  'id': 48,
  'title': 'sit reprehenderit omnis quia',
  'userId': 3},
 {'completed': False,
  'id': 49,
  'title': 'ut necessitatibus aut maiores debitis officia blanditiis velit et',
  'userId': 3},
 {'completed': True,
  'id': 50,
  'title': 'cupiditate necessitatibus ullam aut quis dolor voluptate',
  'userId': 3},
 {'completed': False,
  'id': 51,
  'title': 'distinctio exercitationem ab doloribus',
  'userId': 3},
 {'completed': False,
  'id': 52,
  'title': 'nesciunt dolorum quis recusandae ad pariatur ratione',
  'userId': 3},
 {'completed': False,
  'id': 53,
  'title': 'qui labore est occaecati recusandae aliquid quam',
  'userId': 3},
 {'completed': True,
  'id': 54,
  'title': 'quis et est ut voluptate quam dolor',
  'userId': 3},
 {'completed': True,
  'id': 55,
  'title': 'voluptatum omnis minima qui occaecati provident nulla voluptatem '
           'ratione',
  'userId': 3},
 {'completed': True,
  'id': 56,
  'title': 'deleniti ea temporibus enim',
  'userId': 3},
 {'completed': False,
  'id': 57,
  'title': 'pariatur et magnam ea doloribus similique voluptatem rerum quia',
  'userId': 3},
 {'completed': False,
  'id': 58,
  'title': 'est dicta totam qui explicabo doloribus qui dignissimos',
  'userId': 3},
 {'completed': False,
  'id': 59,
  'title': 'perspiciatis velit id laborum placeat iusto et aliquam odio',
  'userId': 3},
 {'completed': True,
  'id': 60,
  'title': 'et sequi qui architecto ut adipisci',
  'userId': 3},
 {'completed': True,
  'id': 61,
  'title': 'odit optio omnis qui sunt',
  'userId': 4},
 {'completed': False,
  'id': 62,
  'title': 'et placeat et tempore aspernatur sint numquam',
  'userId': 4},
 {'completed': True,
  'id': 63,
  'title': 'doloremque aut dolores quidem fuga qui nulla',
  'userId': 4},
 {'completed': False,
  'id': 64,
  'title': 'voluptas consequatur qui ut quia magnam nemo esse',
  'userId': 4},
 {'completed': False,
  'id': 65,
  'title': 'fugiat pariatur ratione ut asperiores necessitatibus magni',
  'userId': 4},
 {'completed': False,
  'id': 66,
  'title': 'rerum eum molestias autem voluptatum sit optio',
  'userId': 4},
 {'completed': False,
  'id': 67,
  'title': 'quia voluptatibus voluptatem quos similique maiores repellat',
  'userId': 4},
 {'completed': False,
  'id': 68,
  'title': 'aut id perspiciatis voluptatem iusto',
  'userId': 4},
 {'completed': False,
  'id': 69,
  'title': 'doloribus sint dolorum ab adipisci itaque dignissimos aliquam '
           'suscipit',
  'userId': 4},
 {'completed': False,
  'id': 70,
  'title': 'ut sequi accusantium et mollitia delectus sunt',
  'userId': 4},
 {'completed': False, 'id': 71, 'title': 'aut velit saepe ullam', 'userId': 4},
 {'completed': False,
  'id': 72,
  'title': 'praesentium facilis facere quis harum voluptatibus voluptatem eum',
  'userId': 4},
 {'completed': True,
  'id': 73,
  'title': 'sint amet quia totam corporis qui exercitationem commodi',
  'userId': 4},
 {'completed': False,
  'id': 74,
  'title': 'expedita tempore nobis eveniet laborum maiores',
  'userId': 4},
 {'completed': False,
  'id': 75,
  'title': 'occaecati adipisci est possimus totam',
  'userId': 4},
 {'completed': True, 'id': 76, 'title': 'sequi dolorem sed', 'userId': 4},
 {'completed': False,
  'id': 77,
  'title': 'maiores aut nesciunt delectus exercitationem vel assumenda '
           'eligendi at',
  'userId': 4},
 {'completed': False,
  'id': 78,
  'title': 'reiciendis est magnam amet nemo iste recusandae impedit quaerat',
  'userId': 4},
 {'completed': True, 'id': 79, 'title': 'eum ipsa maxime ut', 'userId': 4},
 {'completed': True,
  'id': 80,
  'title': 'tempore molestias dolores rerum sequi voluptates ipsum consequatur',
  'userId': 4},
 {'completed': True, 'id': 81, 'title': 'suscipit qui totam', 'userId': 5},
 {'completed': False,
  'id': 82,
  'title': 'voluptates eum voluptas et dicta',
  'userId': 5},
 {'completed': True,
  'id': 83,
  'title': 'quidem at rerum quis ex aut sit quam',
  'userId': 5},
 {'completed': False,
  'id': 84,
  'title': 'sunt veritatis ut voluptate',
  'userId': 5},
 {'completed': True, 'id': 85, 'title': 'et quia ad iste a', 'userId': 5},
 {'completed': True, 'id': 86, 'title': 'incidunt ut saepe autem', 'userId': 5},
 {'completed': True,
  'id': 87,
  'title': 'laudantium quae eligendi consequatur quia et vero autem',
  'userId': 5},
 {'completed': False,
  'id': 88,
  'title': 'vitae aut excepturi laboriosam sint aliquam et et accusantium',
  'userId': 5},
 {'completed': True, 'id': 89, 'title': 'sequi ut omnis et', 'userId': 5},
 {'completed': True,
  'id': 90,
  'title': 'molestiae nisi accusantium tenetur dolorem et',
  'userId': 5},
 {'completed': True,
  'id': 91,
  'title': 'nulla quis consequatur saepe qui id expedita',
  'userId': 5},
 {'completed': True, 'id': 92, 'title': 'in omnis laboriosam', 'userId': 5},
 {'completed': True,
  'id': 93,
  'title': 'odio iure consequatur molestiae quibusdam necessitatibus quia sint',
  'userId': 5},
 {'completed': False,
  'id': 94,
  'title': 'facilis modi saepe mollitia',
  'userId': 5},
 {'completed': True,
  'id': 95,
  'title': 'vel nihil et molestiae iusto assumenda nemo quo ut',
  'userId': 5},
 {'completed': False,
  'id': 96,
  'title': 'nobis suscipit ducimus enim asperiores voluptas',
  'userId': 5},
 {'completed': False,
  'id': 97,
  'title': 'dolorum laboriosam eos qui iure aliquam',
  'userId': 5},
 {'completed': True,
  'id': 98,
  'title': 'debitis accusantium ut quo facilis nihil quis sapiente '
           'necessitatibus',
  'userId': 5},
 {'completed': False,
  'id': 99,
  'title': 'neque voluptates ratione',
  'userId': 5},
 {'completed': False,
  'id': 100,
  'title': 'excepturi a et neque qui expedita vel voluptate',
  'userId': 5},
 {'completed': False,
  'id': 101,
  'title': 'explicabo enim cumque porro aperiam occaecati minima',
  'userId': 6},
 {'completed': False, 'id': 102, 'title': 'sed ab consequatur', 'userId': 6},
 {'completed': False,
  'id': 103,
  'title': 'non sunt delectus illo nulla tenetur enim omnis',
  'userId': 6},
 {'completed': False,
  'id': 104,
  'title': 'excepturi non laudantium quo',
  'userId': 6},
 {'completed': True,
  'id': 105,
  'title': 'totam quia dolorem et illum repellat voluptas optio',
  'userId': 6},
 {'completed': True,
  'id': 106,
  'title': 'ad illo quis voluptatem temporibus',
  'userId': 6},
 {'completed': False,
  'id': 107,
  'title': 'praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt',
  'userId': 6},
 {'completed': True,
  'id': 108,
  'title': 'a eos eaque nihil et exercitationem incidunt delectus',
  'userId': 6},
 {'completed': True,
  'id': 109,
  'title': 'autem temporibus harum quisquam in culpa',
  'userId': 6},
 {'completed': True, 'id': 110, 'title': 'aut aut ea corporis', 'userId': 6},
 {'completed': False,
  'id': 111,
  'title': 'magni accusantium labore et id quis provident',
  'userId': 6},
 {'completed': False,
  'id': 112,
  'title': 'consectetur impedit quisquam qui deserunt non rerum consequuntur '
           'eius',
  'userId': 6},
 {'completed': False,
  'id': 113,
  'title': 'quia atque aliquam sunt impedit voluptatum rerum assumenda nisi',
  'userId': 6},
 {'completed': False,
  'id': 114,
  'title': 'cupiditate quos possimus corporis quisquam exercitationem beatae',
  'userId': 6},
 {'completed': False, 'id': 115, 'title': 'sed et ea eum', 'userId': 6},
 {'completed': True,
  'id': 116,
  'title': 'ipsa dolores vel facilis ut',
  'userId': 6},
 {'completed': False,
  'id': 117,
  'title': 'sequi quae est et qui qui eveniet asperiores',
  'userId': 6},
 {'completed': False,
  'id': 118,
  'title': 'quia modi consequatur vero fugiat',
  'userId': 6},
 {'completed': False,
  'id': 119,
  'title': 'corporis ducimus ea perspiciatis iste',
  'userId': 6},
 {'completed': False,
  'id': 120,
  'title': 'dolorem laboriosam vel voluptas et aliquam quasi',
  'userId': 6},
 {'completed': True,
  'id': 121,
  'title': 'inventore aut nihil minima laudantium hic qui omnis',
  'userId': 7},
 {'completed': True,
  'id': 122,
  'title': 'provident aut nobis culpa',
  'userId': 7},
 {'completed': False,
  'id': 123,
  'title': 'esse et quis iste est earum aut impedit',
  'userId': 7},
 {'completed': False, 'id': 124, 'title': 'qui consectetur id', 'userId': 7},
 {'completed': False,
  'id': 125,
  'title': 'aut quasi autem iste tempore illum possimus',
  'userId': 7},
 {'completed': True,
  'id': 126,
  'title': 'ut asperiores perspiciatis veniam ipsum rerum saepe',
  'userId': 7},
 {'completed': True,
  'id': 127,
  'title': 'voluptatem libero consectetur rerum ut',
  'userId': 7},
 {'completed': False,
  'id': 128,
  'title': 'eius omnis est qui voluptatem autem',
  'userId': 7},
 {'completed': False,
  'id': 129,
  'title': 'rerum culpa quis harum',
  'userId': 7},
 {'completed': True,
  'id': 130,
  'title': 'nulla aliquid eveniet harum laborum libero alias ut unde',
  'userId': 7},
 {'completed': False, 'id': 131, 'title': 'qui ea incidunt quis', 'userId': 7},
 {'completed': True,
  'id': 132,
  'title': 'qui molestiae voluptatibus velit iure harum quisquam',
  'userId': 7},
 {'completed': True,
  'id': 133,
  'title': 'et labore eos enim rerum consequatur sunt',
  'userId': 7},
 {'completed': False,
  'id': 134,
  'title': 'molestiae doloribus et laborum quod ea',
  'userId': 7},
 {'completed': False,
  'id': 135,
  'title': 'facere ipsa nam eum voluptates reiciendis vero qui',
  'userId': 7},
 {'completed': False,
  'id': 136,
  'title': 'asperiores illo tempora fuga sed ut quasi adipisci',
  'userId': 7},
 {'completed': False, 'id': 137, 'title': 'qui sit non', 'userId': 7},
 {'completed': True,
  'id': 138,
  'title': 'placeat minima consequatur rem qui ut',
  'userId': 7},
 {'completed': False,
  'id': 139,
  'title': 'consequatur doloribus id possimus voluptas a voluptatem',
  'userId': 7},
 {'completed': True,
  'id': 140,
  'title': 'aut consectetur in blanditiis deserunt quia sed laboriosam',
  'userId': 7},
 {'completed': True,
  'id': 141,
  'title': 'explicabo consectetur debitis voluptates quas quae culpa rerum non',
  'userId': 8},
 {'completed': True,
  'id': 142,
  'title': 'maiores accusantium architecto necessitatibus reiciendis ea aut',
  'userId': 8},
 {'completed': False,
  'id': 143,
  'title': 'eum non recusandae cupiditate animi',
  'userId': 8},
 {'completed': False,
  'id': 144,
  'title': 'ut eum exercitationem sint',
  'userId': 8},
 {'completed': False,
  'id': 145,
  'title': 'beatae qui ullam incidunt voluptatem non nisi aliquam',
  'userId': 8},
 {'completed': True,
  'id': 146,
  'title': 'molestiae suscipit ratione nihil odio libero impedit vero totam',
  'userId': 8},
 {'completed': True,
  'id': 147,
  'title': 'eum itaque quod reprehenderit et facilis dolor autem ut',
  'userId': 8},
 {'completed': False,
  'id': 148,
  'title': 'esse quas et quo quasi exercitationem',
  'userId': 8},
 {'completed': False,
  'id': 149,
  'title': 'animi voluptas quod perferendis est',
  'userId': 8},
 {'completed': False,
  'id': 150,
  'title': 'eos amet tempore laudantium fugit a',
  'userId': 8},
 {'completed': True,
  'id': 151,
  'title': 'accusamus adipisci dicta qui quo ea explicabo sed vero',
  'userId': 8},
 {'completed': False,
  'id': 152,
  'title': 'odit eligendi recusandae doloremque cumque non',
  'userId': 8},
 {'completed': False,
  'id': 153,
  'title': 'ea aperiam consequatur qui repellat eos',
  'userId': 8},
 {'completed': True, 'id': 154, 'title': 'rerum non ex sapiente', 'userId': 8},
 {'completed': True,
  'id': 155,
  'title': 'voluptatem nobis consequatur et assumenda magnam',
  'userId': 8},
 {'completed': True,
  'id': 156,
  'title': 'nam quia quia nulla repellat assumenda quibusdam sit nobis',
  'userId': 8},
 {'completed': True,
  'id': 157,
  'title': 'dolorem veniam quisquam deserunt repellendus',
  'userId': 8},
 {'completed': True,
  'id': 158,
  'title': 'debitis vitae delectus et harum accusamus aut deleniti a',
  'userId': 8},
 {'completed': True,
  'id': 159,
  'title': 'debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis',
  'userId': 8},
 {'completed': False,
  'id': 160,
  'title': 'et praesentium aliquam est',
  'userId': 8},
 {'completed': True,
  'id': 161,
  'title': 'ex hic consequuntur earum omnis alias ut occaecati culpa',
  'userId': 9},
 {'completed': True,
  'id': 162,
  'title': 'omnis laboriosam molestias animi sunt dolore',
  'userId': 9},
 {'completed': False,
  'id': 163,
  'title': 'natus corrupti maxime laudantium et voluptatem laboriosam odit',
  'userId': 9},
 {'completed': False,
  'id': 164,
  'title': 'reprehenderit quos aut aut consequatur est sed',
  'userId': 9},
 {'completed': False,
  'id': 165,
  'title': 'fugiat perferendis sed aut quidem',
  'userId': 9},
 {'completed': False,
  'id': 166,
  'title': 'quos quo possimus suscipit minima ut',
  'userId': 9},
 {'completed': False,
  'id': 167,
  'title': 'et quis minus quo a asperiores molestiae',
  'userId': 9},
 {'completed': False,
  'id': 168,
  'title': 'recusandae quia qui sunt libero',
  'userId': 9},
 {'completed': True,
  'id': 169,
  'title': 'ea odio perferendis officiis',
  'userId': 9},
 {'completed': False,
  'id': 170,
  'title': 'quisquam aliquam quia doloribus aut',
  'userId': 9},
 {'completed': True,
  'id': 171,
  'title': 'fugiat aut voluptatibus corrupti deleniti velit iste odio',
  'userId': 9},
 {'completed': False,
  'id': 172,
  'title': 'et provident amet rerum consectetur et voluptatum',
  'userId': 9},
 {'completed': False, 'id': 173, 'title': 'harum ad aperiam quis', 'userId': 9},
 {'completed': False, 'id': 174, 'title': 'similique aut quo', 'userId': 9},
 {'completed': True,
  'id': 175,
  'title': 'laudantium eius officia perferendis provident perspiciatis '
           'asperiores',
  'userId': 9},
 {'completed': False,
  'id': 176,
  'title': 'magni soluta corrupti ut maiores rem quidem',
  'userId': 9},
 {'completed': False,
  'id': 177,
  'title': 'et placeat temporibus voluptas est tempora quos quibusdam',
  'userId': 9},
 {'completed': True,
  'id': 178,
  'title': 'nesciunt itaque commodi tempore',
  'userId': 9},
 {'completed': True,
  'id': 179,
  'title': 'omnis consequuntur cupiditate impedit itaque ipsam quo',
  'userId': 9},
 {'completed': True,
  'id': 180,
  'title': 'debitis nisi et dolorem repellat et',
  'userId': 9},
 {'completed': False,
  'id': 181,
  'title': 'ut cupiditate sequi aliquam fuga maiores',
  'userId': 10},
 {'completed': True,
  'id': 182,
  'title': 'inventore saepe cumque et aut illum enim',
  'userId': 10},
 {'completed': True,
  'id': 183,
  'title': 'omnis nulla eum aliquam distinctio',
  'userId': 10},
 {'completed': False,
  'id': 184,
  'title': 'molestias modi perferendis perspiciatis',
  'userId': 10},
 {'completed': False,
  'id': 185,
  'title': 'voluptates dignissimos sed doloribus animi quaerat aut',
  'userId': 10},
 {'completed': False,
  'id': 186,
  'title': 'explicabo odio est et',
  'userId': 10},
 {'completed': False,
  'id': 187,
  'title': 'consequuntur animi possimus',
  'userId': 10},
 {'completed': True, 'id': 188, 'title': 'vel non beatae est', 'userId': 10},

2. Mostra per pantalla:

La quantitat total de cada recurs.
El codi d'estat de cada petició.

In [ ]:
# Collecting status codes and number of records of all tested resources
status_code_df = pd.DataFrame.from_dict(status_codes, orient='index', columns=['Status_code'])
number_records_df = pd.DataFrame.from_dict(number_records, orient='index', columns=['Number_records'])
# creating a dataframe with collected information
pd.concat([status_code_df, number_records_df], axis=1)

       Status_code  Number_records
posts          200             100
users          200              10
todos          200             200

3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [8]:
er_cod = requests.get('https://jsonplaceholder.typicode.com/names/2698')
if er_cod.status_code == 404:
    print("Inexisting page")
else:
    print("The page is available")

Inexisting page

4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.

Mostra la resposta JSON.
Mostra el codi d'estat.

In [9]:
users_post = requests.post('https://jsonplaceholder.typicode.com/users/', json={"email": "newemail@example.com"})
if users_post.status_code == 201:
    print("Successful")
else:
    print("Insuccessful")

Successful

5. Fes una petició PATCH per modificar parcialment una publicació existent.

Mostra la resposta JSON.
Mostra el codi d'estat.

In [10]:
users_patch = requests.patch('https://jsonplaceholder.typicode.com/users/202', json={"email": "newemail@example.com"})
if users_patch.status_code == 200:
    print("Successful")
else:
    print("Insuccessful")

Successful

6. Fes una petició DELETE sobre una publicació.

Mostra la resposta JSON.
Mostra el codi d'estat.

In [11]:
users_delete = requests.delete('https://jsonplaceholder.typicode.com/users/20')
if users_delete.status_code == 200:
    print("Successfully deleted")
else:
    print(users_delete.status_code, users_delete.text)

Successfully deleted

## Nivell 2

Interacció amb una API pública real
1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

In [ ]:
# Using OpenFDA resource
apiPub = requests.get('https://api.fda.gov/drug/drugsfda.json')
print("Allows GET") if apiPub.status_code == 200 else print("Doesn't allow GET")

Allows GET

2. Llegeix la documentació de l'API:

Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.
Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.
Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

### Target resource: OpenFDA
### Link to API: https://api.fda.gov/
### Structure:
https://api.fda.gov/drug/drugsfda.json?search=products.marketing_status:"Discontinued"&limit=5

base endpoint                           search=                 field:term              limit


#### Endpoint 1:
Searches for records where either FOO or BAR appear anywhere in this field.
search=openfda.manufacturer_name:"FOO+BAR"
search=openfda.manufacturer_name:"AstraZeneca"

#### Endpoint 2:
Counts the tokenized values of this field. Instances of FOO and BAR are counted separately.
count=openfda.manufacturer_name


https://api.fda.gov/drug/drugsfda.json?search=openfda.manufacturer_name:"AstraZeneca"&limit=200

In [52]:
#Using openfda.manufacturer_name:("AstraZeneca") as Endpoint field
manufacturers_FDA = requests.get('https://api.fda.gov/drug/drugsfda.json?search=openfda.manufacturer_name:("AstraZeneca")&limit=200')
#print(manufacturers_FDA.status_code)
manufFDA_data = manufacturers_FDA.json()
res = manufFDA_data["results"] #manufFDA_data.get("results")
print(res)

[{'submissions': [{'submission_type': 'SUPPL', 'submission_number': '46', 'submission_status': 'AP', 'submission_status_date': '20140327', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '36229', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2014/021153s046,021957s015,022101s012lbl.pdf', 'date': '20140401', 'type': 'Label'}, {'id': '4493', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2014/021153Orig1s046,021957Orig1s015,022101Orig1s012ltr.pdf', 'date': '20140328', 'type': 'Letter'}]}, {'submission_type': 'SUPPL', 'submission_number': '6', 'submission_status': 'AP', 'submission_status_date': '20021001', 'submission_class_code': 'MANUF (CMC)', 'submission_class_code_description': 'Manufacturing (CMC)'}, {'submission_type': 'SUPPL', 'submission_number': '60', 'submission_status': 'AP', 'submission_status_date': '20230718', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '74798', 'url': 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2023/021153Orig1s060;021957Orig1s027;022101Orig1s024ltr.pdf', 'date': '20230719', 'type': 'Letter'}, {'id': '74833', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2023/021153s060,021957s027,022101s024lbl.pdf', 'date': '20230720', 'type': 'Label'}, {'id': '74834', 'url': 'https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/021153s060,021957s027,022101s024lbl.pdf#page=40', 'date': '20230720', 'type': 'Medication Guide'}]}, {'submission_type': 'SUPPL', 'submission_number': '38', 'submission_status': 'AP', 'submission_status_date': '20110630', 'review_priority': 'UNKNOWN', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '14522', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2011/022101s007,021153s038,021957s010lbl.pdf', 'date': '20110706', 'type': 'Label'}, {'id': '26923', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2011/022101s007,021153s038,021957s010,021689s020ltr.pdf', 'date': '20110706', 'type': 'Letter'}]}, {'submission_type': 'SUPPL', 'submission_number': '52', 'submission_status': 'AP', 'submission_status_date': '20161024', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '45660', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2016/021153Orig1s052,022101Orig1s016,021957Orig1s019ltr.pdf', 'date': '20161026', 'type': 'Letter'}, {'id': '45693', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2016/021153s052_22101s016_21957s019lbl.pdf', 'date': '20161028', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '4', 'submission_status': 'AP', 'submission_status_date': '20030227', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '26915', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2003/21153slr004ltr.pdf', 'date': '20030310', 'type': 'Letter'}]}, {'submission_type': 'SUPPL', 'submission_number': '44', 'submission_status': 'AP', 'submission_status_date': '20121128', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '14526', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2012/021153s044,021957s014,022101s011lbl.pdf', 'date': '20121210', 'type': 'Label'}, {'id': '26925', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2012/021153Orig1s044,021957Orig1s014,022101Orig1s011ltr.pdf', 'date': '20121129', 'type': 'Letter'}]}, {'submission_type': 'SUPPL', 'submission_number': '36', 'submission_status': 'AP', 'submission_status_date': '20100903', 'review_priority': 'UNKNOWN', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '4490', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2010/021153s036,021957s009,022101s006ltr.pdf', 'date': '20100909', 'type': 'Letter'}, {'id': '36228', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2010/021153s036,021957s009,022101s006lbl.pdf', 'date': '20100910', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '50', 'submission_status': 'AP', 'submission_status_date': '20141219', 'review_priority': '901 REQUIRED', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '26927', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2014/021153Orig1s050,021957Orig1s017,022101Orig1s014ltr.pdf', 'date': '20141224', 'type': 'Letter'}, {'id': '36230', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2014/022101s014021957s017021153s050lbl.pdf', 'date': '20141229', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '2', 'submission_status': 'AP', 'submission_status_date': '20010516', 'submission_class_code': 'MANUF (CMC)', 'submission_class_code_description': 'Manufacturing (CMC)'}, {'submission_type': 'SUPPL', 'submission_number': '28', 'submission_status': 'AP', 'submission_status_date': '20070427', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '14518', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2007/021153s027s028,021689s008s011lbl.pdf', 'date': '20070501', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '42', 'submission_status': 'AP', 'submission_status_date': '20121009', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '4491', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2012/021153Orig1s042,021957Orig1s012,022101Orig1s009ltr.pdf', 'date': '20121011', 'type': 'Letter'}, {'id': '14524', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2012/021153s042,021957s012,022101s009lbl.pdf', 'date': '20121012', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '34', 'submission_status': 'AP', 'submission_status_date': '20100304', 'review_priority': 'UNKNOWN', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '4488', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2010/021153s034,021689s015,021957s007,022101s004ltr.pdf', 'date': '20100308', 'type': 'Letter'}, {'id': '14520', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2010/022101s004,021153s034,021957s007,021689s015lbl.pdf', 'date': '20100305', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '40', 'submission_status': 'AP', 'submission_status_date': '20120120', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '14523', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2012/021153s040,021957s011,022101s008lbl.pdf', 'date': '20120124', 'type': 'Label'}, {'id': '26924', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2012/022101s008,021153s040,021957s011ltr.pdf', 'date': '20120124', 'type': 'Letter'}]}, {'submission_type': 'ORIG', 'submission_number': '1', 'submission_status': 'AP', 'submission_status_date': '20010220', 'review_priority': 'PRIORITY', 'submission_class_code': 'TYPE 2', 'submission_class_code_description': 'Type 2 - New Active Ingredient', 'application_docs': [{'id': '41988', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/nda/2001/21154_Nexium.html', 'date': '20010220', 'type': 'Review'}, {'id': '44101', 'url': 'http://www.fda.gov/Drugs/DrugSafety/InformationbyDrugClass/ucm213259.htm', 'date': '20111220', 'type': 'Other Important Information from FDA'}, {'id': '51721', 'url': 'https://www.accessdata.fda.gov/drugsatfda_docs/pediatric/021153--Esomeprazole-Original-WR.pdf', 'date': '19000101', 'type': 'Pediatric Written Request'}, {'id': '51722', 'url': 'https://www.accessdata.fda.gov/drugsatfda_docs/pediatric/021153-Esomeprazole-Amendment-1-WR.pdf', 'date': '19000101', 'type': 'Pediatric Amendment 1'}, {'id': '51723', 'url': 'https://www.accessdata.fda.gov/drugsatfda_docs/pediatric/021153-Esomeprazole-Amendment-2-WR.pdf', 'date': '19000101', 'type': 'Pediatric Amendment 2'}, {'id': '51724', 'url': 'https://www.accessdata.fda.gov/drugsatfda_docs/pediatric/021153-Esomeprazole-Amendment-3-WR.pdf', 'date': '19000101', 'type': 'Pediatric Amendment 3'}, {'id': '51725', 'url': 'https://www.accessdata.fda.gov/drugsatfda_docs/pediatric/021153_esomeprazole_(Nexium)_Amendment_5_WR.pdf', 'date': '19000101', 'type': 'Pediatric Amendment 5'}, {'id': '67176', 'url': 'https://www.accessdata.fda.gov/drugsatfda_docs/pediatric/21153_esomeprazole_(Nexium)_Amendment_4_WR.pdf', 'date': '19000101', 'type': 'Pediatric Amendment 4'}, {'id': '26914', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/nda/2001/21154_Nexium_Approv.pdf', 'date': '20010220', 'type': 'Letter'}, {'id': '36222', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2001/21153lbl.pdf', 'date': '20010220', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '24', 'submission_status': 'AP', 'submission_status_date': '20060915', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '4485', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2006/021153s024ltr.pdf', 'date': '20060920', 'type': 'Letter'}, {'id': '14516', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2006/021153s024lbl.pdf', 'date': '20060918', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '22', 'submission_status': 'AP', 'submission_status_date': '20060428', 'review_priority': 'PRIORITY', 'submission_class_code': 'EFFICACY', 'submission_class_code_description': 'Efficacy', 'application_docs': [{'id': '14515', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2006/021153s022lbl.pdf', 'date': '20060502', 'type': 'Label'}, {'id': '26919', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2006/021153s022LTR.pdf', 'date': '20060502', 'type': 'Letter'}]}, {'submission_type': 'SUPPL', 'submission_number': '20', 'submission_status': 'AP', 'submission_status_date': '20050606', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '4483', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2005/021153s020ltr.pdf', 'date': '20050608', 'type': 'Letter'}, {'id': '14513', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2005/021153s020lbl.pdf', 'date': '20050608', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '59', 'submission_status': 'AP', 'submission_status_date': '20220304', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '70411', 'url': 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2022/021153Orig1s059; 021957Orig1s026; 022101Orig1s023ltr.pdf', 'date': '20220307', 'type': 'Letter'}, {'id': '70456', 'url': 'https://www.accessdata.fda.gov/drugsatfda_docs/label/2022/021153s059,021957s026,022101s023lbl.pdf', 'date': '20220310', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '57', 'submission_status': 'AP', 'submission_status_date': '20201127', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '65379', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2020/021153Orig1s057;021957Orig1s024;022101Orig1s021ltr.pdf', 'date': '20201130', 'type': 'Letter'}, {'id': '65406', 'url': 'https://www.accessdata.fda.gov/drugsatfda_docs/label/2020/021153s057,021957s024,022101s021lbl.pdf', 'date': '20201130', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '49', 'submission_status': 'AP', 'submission_status_date': '20140225', 'review_priority': '901 REQUIRED', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '14527', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2014/021153s049,021957s016,022101s013lbl.pdf', 'date': '20140305', 'type': 'Label'}, {'id': '26926', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2014/021153Orig1s049,021957Orig1s016,022101Orig1s013ltr.pdf', 'date': '20140227', 'type': 'Letter'}]}, {'submission_type': 'SUPPL', 'submission_number': '47', 'submission_status': 'AP', 'submission_status_date': '20131004', 'submission_class_code': 'MANUF (CMC)', 'submission_class_code_description': 'Manufacturing (CMC)', 'application_docs': [{'id': '21481', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/nda/2013/021153Orig1s047.pdf', 'date': '20140805', 'type': 'Review'}]}, {'submission_type': 'SUPPL', 'submission_number': '53', 'submission_status': 'AP', 'submission_status_date': '20180607', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '54498', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2018/021153s053,022101s017,021957s020lbl.pdf', 'date': '20180611', 'type': 'Label'}, {'id': '54568', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2018/021153Orig1s053,022101Orig1s017,021957Orig1s020ltr.pdf', 'date': '20180614', 'type': 'Letter'}]}, {'submission_type': 'SUPPL', 'submission_number': '45', 'submission_status': 'AP', 'submission_status_date': '20130617', 'submission_class_code': 'MANUF (CMC)', 'submission_class_code_description': 'Manufacturing (CMC)', 'application_docs': [{'id': '21480', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/nda/2013/021153Orig1s045.pdf', 'date': '20140805', 'type': 'Review'}]}, {'submission_type': 'SUPPL', 'submission_number': '5', 'submission_status': 'AP', 'submission_status_date': '20020920', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '41989', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/nda/2002/21-153S005_review.pdf', 'date': '20040414', 'type': 'Review'}, {'id': '4481', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2002/21153slr005ltr.pdf', 'date': '20020920', 'type': 'Letter'}]}, {'submission_type': 'SUPPL', 'submission_number': '51', 'submission_status': 'AP', 'submission_status_date': '20161220', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '46480', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2016/021957Orig1s018,021153Orig1s051,022101Orig1s015ltr.pdf', 'date': '20161222', 'type': 'Letter'}, {'id': '46488', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2016/021153s051,021957s018,022101s015lbl.pdf', 'date': '20161221', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '29', 'submission_status': 'AP', 'submission_status_date': '20080111', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '26921', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2008/021957s001,021153s029ltr.pdf', 'date': '20080118', 'type': 'Letter'}]}, {'submission_type': 'SUPPL', 'submission_number': '3', 'submission_status': 'AP', 'submission_status_date': '20020314', 'submission_class_code': 'MANUF (CMC)', 'submission_class_code_description': 'Manufacturing (CMC)'}, {'submission_type': 'SUPPL', 'submission_number': '43', 'submission_status': 'AP', 'submission_status_date': '20120928', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '4492', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2012/021153Orig1s043,021957Orig1s013,022101Orig1s010ltr.pdf', 'date': '20121002', 'type': 'Letter'}, {'id': '14525', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2012/021153s043_02195sS013_02210s010lbl.pdf', 'date': '20121001', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '35', 'submission_status': 'AP', 'submission_status_date': '20110621', 'review_priority': 'UNKNOWN', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '4489', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2011/022101s005,021153s035,021957s008,021689s016ltr.pdf', 'date': '20110627', 'type': 'Letter'}, {'id': '14521', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2011/022101s005,021153s035,021957s008lbl.pdf', 'date': '20110629', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '1', 'submission_status': 'AP', 'submission_status_date': '20010516', 'submission_class_code': 'MANUF (CMC)', 'submission_class_code_description': 'Manufacturing (CMC)'}, {'submission_type': 'SUPPL', 'submission_number': '27', 'submission_status': 'AP', 'submission_status_date': '20070427', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '4486', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2007/021153s027, 021689s008ltr.pdf', 'date': '20070501', 'type': 'Letter'}, {'id': '36226', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2007/021153s027s028,021689s008s011lbl.pdf', 'date': '20070501', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '19', 'submission_status': 'AP', 'submission_status_date': '20041124', 'review_priority': 'UNKNOWN', 'submission_class_code': 'EFFICACY', 'submission_class_code_description': 'Efficacy', 'application_docs': [{'id': '26917', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2004/21153s019ltr.pdf', 'date': '20041202', 'type': 'Letter'}, {'id': '36224', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2004/21153s019lbl.pdf', 'date': '20041203', 'type': 'Label'}]}, {'submission_type': 'SUPPL', 'submission_number': '33', 'submission_status': 'AP', 'submission_status_date': '20091009', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '36227', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2009/021153s033,022101s003lbl.pdf', 'date': '20091014', 'type': 'Label'}, {'id': '4487', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2009/021153s033,022101s003ltr.pdf', 'date': '20091125', 'type': 'Letter'}]}, {'submission_type': 'SUPPL', 'submission_number': '25', 'submission_status': 'AP', 'submission_status_date': '20060926', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '14517', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2006/021153s025lbl.pdf', 'date': '20060927', 'type': 'Label'}, {'id': '26920', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2006/021153s025ltr.pdf', 'date': '20061002', 'type': 'Letter'}]}, {'submission_type': 'SUPPL', 'submission_number': '31', 'submission_status': 'AP', 'submission_status_date': '20090115', 'review_priority': 'STANDARD', 'submission_class_code': 'LABELING', 'submission_class_code_description': 'Labeling', 'application_docs': [{'id': '14519', 'url': 'http://www.accessdata.fda.gov/drugsatfda_docs/label/2009/021153s031,021957s003,022101s001lbl.pdf', '

In [ ]:
#Using 'openfda.manufacturer_name:("AstraZeneca")' and 'count=openfda.manufacturer_name.exact' as Endpoint fields
AZ_count_FDA = requests.get('https://api.fda.gov/drug/drugsfda.json?search=openfda.manufacturer_name:("AstraZeneca")&count=openfda.manufacturer_name.exact')
AZ_count_data = AZ_count_FDA.json()
AZ_count = AZ_count_data["results"]
print(AZ_count)

[{'term': 'AstraZeneca Pharmaceuticals LP', 'count': 34}, {'term': 'H2-Pharma, LLC', 'count': 2}, {'term': 'Prasco Laboratories', 'count': 2}]

3. Fes una petició GET senzilla:

Mostra el codi d'estat de la resposta.
Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [58]:
print(f"{type(res)}, \n {res[0]}")

<class 'list'>,

4. Converteix les dades a un DataFrame de pandas:

Mostra les primeres files del DataFrame.

In [67]:
pprint.pprint(res[0].keys())

dict_keys(['submissions', 'application_number', 'sponsor_name', 'openfda', 'products'])

In [ ]:
#Checking the number of records in 'submissions' field
print(len(res[0]['submissions']))
#saving the data into a dataframe
submissions = pd.DataFrame(json_normalize(res[0]['submissions']))
# visualisation of the dataframe
display(submissions)

42

,submission_type,submission_number,submission_status,submission_status_date,review_priority,submission_class_code,submission_class_code_description,application_docs
0,SUPPL,46,AP,20140327,STANDARD,LABELING,Labeling,"[{'id': '36229', 'url': 'http://www.accessdata..."
1,SUPPL,6,AP,20021001,NaN,MANUF (CMC),Manufacturing (CMC),NaN
2,SUPPL,60,AP,20230718,STANDARD,LABELING,Labeling,"[{'id': '74798', 'url': 'https://www.accessdat..."
3,SUPPL,38,AP,20110630,UNKNOWN,LABELING,Labeling,"[{'id': '14522', 'url': 'http://www.accessdata..."
4,SUPPL,52,AP,20161024,STANDARD,LABELING,Labeling,"[{'id': '45660', 'url': 'http://www.accessdata..."
5,SUPPL,4,AP,20030227,STANDARD,LABELING,Labeling,"[{'id': '26915', 'url': 'http://www.accessdata..."
6,SUPPL,44,AP,20121128,STANDARD,LABELING,Labeling,"[{'id': '14526', 'url': 'http://www.accessdata..."
7,SUPPL,36,AP,20100903,UNKNOWN,LABELING,Labeling,"[{'id': '4490', 'url': 'http://www.accessdata...."
8,SUPPL,50,AP,20141219,901 REQUIRED,LABELING,Labeling,"[{'id': '26927', 'url': 'http://www.accessdata..."
9,SUPPL,2,AP,20010516,NaN,MANUF (CMC),Manufacturing (CMC),NaN
10,SUPPL,28,AP,20070427,NaN,LABELING,Labeling,"[{'id': '14518', 'url': 'http://www.accessdata..."
11,SUPPL,42,AP,20121009,STANDARD,LABELING,Labeling,"[{'id': '4491', 'url': 'http://www.accessdata...."
12,SUPPL,34,AP,20100304,UNKNOWN,LABELING,Labeling,"[{'id': '4488', 'url': 'http://www.accessdata...."
13,SUPPL,40,AP,20120120,STANDARD,LABELING,Labeling,"[{'id': '14523', 'url': 'http://www.accessdata..."
14,ORIG,1,AP,20010220,PRIORITY,TYPE 2,Type 2 - New Active Ingredient,"[{'id': '41988', 'url': 'http://www.accessdata..."
15,SUPPL,24,AP,20060915,STANDARD,LABELING,Labeling,"[{'id': '4485', 'url': 'http://www.accessdata...."
16,SUPPL,22,AP,20060428,PRIORITY,EFFICACY,Efficacy,"[{'id': '14515', 'url': 'http://www.accessdata..."
17,SUPPL,20,AP,20050606,STANDARD,LABELING,Labeling,"[{'id': '4483', 'url': 'http://www.accessdata...."
18,SUPPL,59,AP,20220304,STANDARD,LABELING,Labeling,"[{'id': '70411', 'url': 'https://www.accessdat..."
19,SUPPL,57,AP,20201127,STANDARD,LABELING,Labeling,"[{'id': '65379', 'url': 'http://www.accessdata..."
20,SUPPL,49,AP,20140225,901 REQUIRED,LABELING,Labeling,"[{'id': '14527', 'url': 'http://www.accessdata..."
21,SUPPL,47,AP,20131004,NaN,MANUF (CMC),Manufacturing (CMC),"[{'id': '21481', 'url': 'http://www.accessdata..."
22,SUPPL,53,AP,20180607,STANDARD,LABELING,Labeling,"[{'id': '54498', 'url': 'http://www.accessdata..."
23,SUPPL,45,AP,20130617,NaN,MANUF (CMC),Manufacturing (CMC),"[{'id': '21480', 'url': 'http://www.accessdata..."
24,SUPPL,5,AP,20020920,STANDARD,LABELING,Labeling,"[{'id': '41989', 'url': 'http://www.accessdata..."
25,SUPPL,51,AP,20161220,STANDARD,LABELING,Labeling,"[{'id': '46480', 'url': 'http://www.accessdata..."
26,SUPPL,29,AP,20080111,STANDARD,LABELING,Labeling,"[{'id': '26921', 'url': 'http://www.accessdata..."
27,SUPPL,3,AP,20020314,NaN,MANUF (CMC),Manufacturing (CMC),NaN
28,SUPPL,43,AP,20120928,STANDARD,LABELING,Labeling,"[{'id': '4492', 'url': 'http://www.accessdata...."
29,SUPPL,35,AP,20110621,UNKNOWN,LABELING,Labeling,"[{'id': '4489', 'url': 'http://www.accessdata...."
30,SUPPL,1,AP,20010516,NaN,MANUF (CMC),Manufacturing (CMC),NaN
31,SUPPL,27,AP,20070427,STANDARD,LABELING,Labeling,"[{'id': '4486', 'url': 'http://www.accessdata...."
32,SUPPL,19,AP,20041124,UNKNOWN,EFFICACY,Efficacy,"[{'id': '26917', 'url': 'http://www.accessdata..."
33,SUPPL,33,AP,20091009,STANDARD,LABELING,Labeling,"[{'id': '36227', 'url': 'http://www.accessdata..."
34,SUPPL,25,AP,20060926,STANDARD,LABELING,Labeling,"[{'id': '14517', 'url': 'http://www.accessdata..."
35,SUPPL,31,AP,20090115,STANDARD,LABELING,Labeling,"[{'id': '14519', 'url': 'http://www.accessdata..."
36,SUPPL,23,AP,20061011,UNKNOWN,EFFICACY,Efficacy,"[{'id': '4484', 'url': 'http://www.accessdata...."
37,SUPPL,15,AP,20040423,STANDARD,LABELING,Labeling,"[{'id': '41991', 'url': 'http://www.accessdata..."
38,SUPPL,21,AP,20060216,STANDARD,LABELING,Labeling,"[{'id': '14514', 'url': 'http://www.accessdata..."
39,SUPPL,56,AP,20210825,STANDARD,LABELING,Labeling,"[{'id': '68477', 'url': 'https://www.accessdat..."
40,SUPPL,48,AP,20140214,NaN,MANUF (CMC),Manufacturing (CMC),"[{'id': '41992', 'url': 'http://www.accessdata..."
41,SUPPL,8,AP,20040109,STANDARD,LABELING,Labeling,"[{'id': '36223', 'url': 'http://www.accessdata..."

## Nivell 3
API d'Open Data Barcelona

### Resource:
https://opendata-ajuntament.barcelona.cat/data/ca/dataset/equipament-sanitat/resource/2bf62aa3-63c8-4177-b57a-e32a8c7eb275

Es pot accedir a la API de dades a través de les següents accions de la API de CKAN.

Crea	https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_create

Actualizar / Inserir	https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_upsert

Consulta	https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search

Consulta (amb SQL)	https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search_sql

#### Consulta
Exemple de consulta (primers 5 resultats)
https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id=2bf62aa3-63c8-4177-b57a-e32a8c7eb275&limit=5

Exemple de consulta (resultats que contenen 'jones')
https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id=2bf62aa3-63c8-4177-b57a-e32a8c7eb275&q=jones

Exemple de consulta (amb SQL)
https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search_sql?sql=SELECT * from "2bf62aa3-63c8-4177-b57a-e32a8c7eb275" WHERE "title" LIKE 'jones'


#### Exemple: Python
import urllib

url = 'https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id=2bf62aa3-63c8-4177-b57a-e32a8c7eb275&limit=5&q=title:jones'

fileobj = urllib.urlopen(url)

print fileobj.read()

1. Utilitza l’API d’Open Data BCN per:

Cercar un dataset del teu interès mitjançant package_search i package_show.

In [90]:
# Inputs
keyword = 'sanitat'
url = f"https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_search?q={keyword}"

#API request
kw_search = requests.get(url)

data_search = kw_search.json()
#Checking number of fields
print(len(data_search))
# Checking which keys are
print(data_search.keys())
#Cheking number of fields in 'results' from 'result'
print(len(data_search["result"]["results"]))
#checking type of object it is
print(type(data_search["result"]["results"]))

#Visualising the content
for dtset in data_search["result"]["results"]:
    pprint.pprint(dtset)

3
dict_keys(['help', 'success', 'result'])
4
<class 'list'>
{'ODS_Colateral1_agenda_2030': 'N/A',
 'ODS_Colateral2_agenda_2030': 'N/A',
 'ODS_Principal_agenda_2030': 'ODS 3: Salut i benestar',
 'api': 'Yes',
 'author': "Gerència d'Àrea Agenda 2030, Transició Digital i Esports",
 'author_email': None,
 'code': 'sanitat farmacies',
 'creator_user_id': 'f4b16b79-1c06-43ee-a5e9-b3df1316fcad',
 'dataset_fields_description': '',
 'decalatgeNum': 'N/A',
 'department': "Direcció de Serveis d'Informació i Atenció Ciutadana",
 'extras': [{'key': '*00.', 'value': '__ESTRUCTURA RECURS FORMAT .CSV__'},
            {'key': '*01.',
             'value': "Consultar __'Definició de camps'__ al dataset __[ "
                      'Miradors a la ciutat de '
                      'Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/np-nasia-miradors)__'},
            {'key': '00.', 'value': '__ESTRUCTURA RECURS EN FORMAT .JSON__'},
            {'key': '01.',
             'value': "Consultar __'Definició de camps'__ al dataset __[LLista "
                      "d'esdeveniments diaris de la ciutat de "
                      'Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/agenda-diaria)__  '}],
 'fecha_publicacion': '2019-05-21',
 'frequency': 'SETMANAL',
 'fuente': 'Ajuntament de Barcelona',
 'geolocation': 'Yes_with_map_view',
 'groups': [],
 'hide_url': 'Yes',
 'historical': 'No',
 'id': '3b65cc32-2299-4638-8050-e9349a2b6ca0',
 'isopen': True,
 'license_id': 'CC-BY-4.0',
 'license_title': 'Creative Commons Attribution 4.0',
 'license_url': 'https://creativecommons.org/licenses/by/4.0/',
 'load_type': 'link_extern',
 'long_format': 'No',
 'mar_od': 'No',
 'metadata_modified': '2023-10-31T08:35:45.017283',
 'name': 'sanitat-farmacies',
 'notes': 'Information on the pharmacies of the city of Barcelona.',
 'notes_translated': {'ca': 'Informació de les farmàcies de la ciutat de '
                            'Barcelona.',
                      'en': 'Information on the pharmacies of the city of '
                            'Barcelona.',
                      'es': 'Información de las farmacias de la ciudad de '
                            'Barcelona.'},
 'num_resources': 2,
 'num_tags': 4,
 'organization': {'approval_status': 'approved',
                  'code': 'societat-i-benestar',
                  'created': '2017-01-24T16:55:06.300630',
                  'description': 'Society and Welfare',
                  'description_translated': {'ca': 'Societat i benestar',
                                             'en': 'Society and Welfare',
                                             'es': 'Sociedad y bienestar'},
                  'display_name': 'Societat i benestar',
                  'groups': [{'capacity': 'public', 'name': 'poblacio'}],
                  'id': '9d5ac838-6f5e-4e74-8cec-6714ef289887',
                  'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon-families',
                  'image_url': 'bcn-icon-families',
                  'is_organization': True,
                  'name': 'societat-i-benestar',
                  'num_followers': 0,
                  'package_count': 27,
                  'parent': {'approval_status': 'approved',
                             'code': 'poblacio',
                             'created': '2017-01-24T16:55:07.191598',
                             'description': 'Population',
                             'description_translated': {'ca': 'Població',
                                                        'en': 'Population',
                                                        'es': 'Población'},
                             'display_name': 'Població',
                             'groups': [],
                             'id': '3fa4d9dd-5e2c-46fa-ba43-298b6900bb5f',
                             'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon2-poblacio',
                             'image_url': 'bcn-icon2-poblacio',
                             'is_organization': True,
                             'name': 'poblacio',
                             'num_followers': 0,
                             'package_count': 0,
                             'revision_id': 'e0b0ec67-528e-4be2-9425-f9d0bc3c0f71',
                             'state': 'active',
                             'title': 'Population',
                             'title_translated': {'ca': 'Població',
                                                  'en': 'Population',
                                                  'es': 'Población'},
                             'type': 'organization'},
                  'revision_id': '614cab6b-639b-49e5-a52c-446758902756',
                  'state': 'active',
                  'tematica_nti': 'sociedad-bienestar',
                  'title': 'Society and Welfare',
                  'title_translated': {'ca': 'Societat i benestar',
                                       'en': 'Society and Welfare',
                                       'es': 'Sociedad y bienestar'},
                  'type': 'organization'},
 'owner_org': '9d5ac838-6f5e-4e74-8cec-6714ef289887',
 'private': False,
 'relationships_as_object': [],
 'relationships_as_subject': [],
 'resources': [{'api_access_number': '280',
                'api_access_number_absolute': '329',
                'cache_last_updated': None,
                'cache_url': None,
                'column_types': '',
                'created': '2021-03-25T16:45:18.720828',
                'datastore_active': True,
                'description': '',
                'downloads': '1766',
                'downloads_absolute': '2323',
                'format': 'CSV',
                'hash': '',
                'hide_url': 'Yes',
                'id': 'b89329ea-81ea-496c-9cd0-6758336e6c20',
                'last_modified': '2023-10-31T09:35:28.912729',
                'map_visualization_res': 'data_explorer_map',
                'mimetype': None,
                'mimetype_inner': None,
                'name': 'opendatabcn_sanitat_farmacies.csv',
                'package_id': '3b65cc32-2299-4638-8050-e9349a2b6ca0',
                'position': 0,
                'qa': "{'updated': '2026-03-25T02:13:29.308997', "
                      "'openness_score': 3, 'archival_timestamp': None, "
                      "'format': u'CSV', 'created': "
                      "'2021-03-26T02:10:12.111634', 'resource_timestamp': "
                      "None, 'openness_score_reason': u'This file had not been "
                      'downloaded at the time of scoring it. URL extension '
                      '"csv" relates to format "CSV" and receives score: 3.\'}',
                'resource_type': None,
                'revision_id': 'dfbba2b5-7370-4162-9315-1ff594415107',
                'size': '917588',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3b65cc32-2299-4638-8050-e9349a2b6ca0/resource/b89329ea-81ea-496c-9cd0-6758336e6c20/download',
                'url_type': None},
               {'api_access_number': '2',
                'api_access_number_absolute': '2',
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2021-06-03T13:50:58.693341',
                'datastore_active': False,
                'description': '',
                'downloads': '1220',
                'downloads_absolute': '1495',
                'format': 'JSON',
                'hash': '',
                'hide_url': 'Yes',
                'id': 'f4fe5904-0214-4e86-a62f-9e03a5dcceaa',
                'last_modified': '2023-10-31T09:35:44.984410',
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': 'opendatabcn_sanitat_farmacies-js.json',
                'package_id': '3b65cc32-2299-4638-8050-e9349a2b6ca0',
                'position': 1,
                'qa': "{'updated': '2026-03-25T02:13:29.334594', "
                      "'openness_score': 3, 'archival_timestamp': None, "
                      "'format': u'JSON', 'created': "
                      "'2021-06-04T02:10:00.879401', 'resource_timestamp': "
                      "None, 'openness_score_reason': u'This file had not been "
                      'downloaded at the time of scoring it. URL extension '
                      '"json" relates to format "JSON" and receives score: '
                      "3.'}",
                'resource_type': None,
                'revision_id': 'dfbba2b5-7370-4162-9315-1ff594415107',
                'size': '47299779',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3b65cc32-2299-4638-8050-e9349a2b6ca0/resource/f4fe5904-0214-4e86-a62f-9e03a5dcceaa/download',
                'url_type': None}],
 'revision_id': 'a4a7c4b3-ed76-4b13-81a7-59d70732be6c',
 'state': 'active',
 'tag': 'Sanitat,Farmàcies,Serveis sanitaris,Plànol BCN',
 'tags': [{'display_name': 'Farmàcies',
           'id': '82ea6d17-1d86-4a34-8d0d-8e9eb31e18a6',
           'name': 'Farmàcies',
           'state': 'active',
           'vocabulary_id': None},
          {'display_name': 'Plànol BCN',
           'id': 'f5a5a7bb-56eb-4380-9e36-18c473662f33',
           'name': 'Plànol BCN',
           'state': 'active',
           'vocabulary_id': None},
          {'display_name': 'Sanitat',
           'id': 'b6ddcdbc-db70-4c48-b796-d5158601f444',
           'name': 'Sanitat',
           'state': 'active',
           'vocabulary_id': None},
          {'display_name': 'Serveis sanitaris',
           'id': '6ba2455b-a0c8-4910-8946-e14253ae9ea7',
           'name': 'Serveis sanitaris',
           'state': 'active',
           'vocabulary_id': None}],
 'title': 'Pharmacies in the city of Barcelona',
 'title_translated': {'ca': 'Farmàcies de la ciutat de Barcelona',
                      'en': 'Pharmacies in the city of Barcelona',
                      'es': 'Farmacias de la ciudad de Barcelona'},
 'token_required': 'No',
 'type': 'dataset',
 'url': None,
 'url_tornada': {'ca': 'https://w33.bcn.cat/planolBCN/ca',
                 'en': 'https://w33.bcn.cat/planolBCN/en',
                 'es': 'https://w33.bcn.cat/planolBCN/es'},
 'version': ''}
{'ODS_Colateral1_agenda_2030': 'N/A',
 'ODS_Colateral2_agenda_2030': 'N/A',
 'ODS_Principal_agenda_2030': 'ODS 3: Salut i benestar',
 'api': 'Yes',
 'author': "Gerència d'Àrea Agenda 2030, Transició Digital i Esports",
 'author_email': None,
 'code': 'sanitat hospitals atencio primaria',
 'creator_user_id': 'f4b16b79-1c06-43ee-a5e9-b3df1316fcad',
 'dataset_fields_description': '',
 'decalatgeNum': 'N/A',
 'department': "Direcció de Serveis d'Informació i Atenció Ciutadana",
 'extras': [{'key': '*00.', 'value': '__ESTRUCTURA RECURS FORMAT .CSV__'},
            {'key': '*01.',
             'value': "Consultar __'Definició de camps'__ al dataset __[ "
                      'Miradors a la ciutat de '
                      'Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/np-nasia-miradors)__'},
            {'key': '00.', 'value': '__ESTRUCTURA RECURS EN FORMAT .JSON__'},
            {'key': '01.',
             'value': "Consultar __'Definició de camps'__ al dataset __[LLista "
                      "d'esdeveniments diaris de la ciutat de "
                      'Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/agenda-diaria)__    '}],
 'fecha_publicacion': '2019-05-21',
 'frequency': 'SETMANAL',
 'fuente': 'Ajuntament de Barcelona',
 'geolocation': 'Yes_with_map_view',
 'groups': [],
 'hide_url': 'Yes',
 'historical': 'No',
 'id': 'b959dce3-4862-4697-a158-63f8b15ed4f3',
 'isopen': True,
 'license_id': 'CC-BY-4.0',
 'license_title': 'Creative Commons Attribution 4.0',
 'license_url': 'https://creativecommons.org/licenses/by/4.0/',
 'load_type': 'link_extern',
 'long_format': 'No',
 'mar_od': 'No',
 'metadata_modified': '2023-10-31T08:36:42.614612',
 'name': 'sanitat-hospitals-atencio-primaria',
 'notes': 'List of hospitals and centres of primary health service of the city '
          'of Barcelona',
 'notes_translated': {'ca': "Llista d'hospitals i Centres d'Atenció Primària "
                            'de la ciutat de Barcelona',
                      'en': 'List of hospitals and centres of primary health '
                            'service of the city of Barcelona',
                      'es': 'Lista de hospitales y Centros de Atención '
                            'Primaria de la ciudad de Barcelona'},
 'num_resources': 2,
 'num_tags': 6,
 'organization': {'approval_status': 'approved',
                  'code': 'societat-i-benestar',
                  'created': '2017-01-24T16:55:06.300630',
                  'description': 'Society and Welfare',
                  'description_translated': {'ca': 'Societat i benestar',
                                             'en': 'Society and Welfare',
                                             'es': 'Sociedad y bienestar'},
                  'display_name': 'Societat i benestar',
                  'groups': [{'capacity': 'public', 'name': 'poblacio'}],
                  'id': '9d5ac838-6f5e-4e74-8cec-6714ef289887',
                  'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon-families',
                  'image_url': 'bcn-icon-families',
                  'is_organization': True,
                  'name': 'societat-i-benestar',
                  'num_followers': 0,
                  'package_count': 27,
                  'parent': {'approval_status': 'approved',
                             'code': 'poblacio',
                             'created': '2017-01-24T16:55:07.191598',
                             'description': 'Population',
                             'description_translated': {'ca': 'Població',
                                                        'en': 'Population',
                                                        'es': 'Población'},
                             'display_name': 'Població',
                             'groups': [],
                             'id': '3fa4d9dd-5e2c-46fa-ba43-298b6900bb5f',
                             'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon2-poblacio',
                             'image_url': 'bcn-icon2-poblacio',
                             'is_organization': True,
                             'name': 'poblacio',
                             'num_followers': 0,
                             'package_count': 0,
                             'revision_id': 'e0b0ec67-528e-4be2-9425-f9d0bc3c0f71',
                             'state': 'active',
                             'title': 'Population',
                             'title_translated': {'ca': 'Població',
                                                  'en': 'Population',
                                                  'es': 'Población'},
                             'type': 'organization'},
                  'revision_id': '614cab6b-639b-49e5-a52c-446758902756',
                  'state': 'active',
                  'tematica_nti': 'sociedad-bienestar',
                  'title': 'Society and Welfare',
                  'title_translated': {'ca': 'Societat i benestar',
                                       'en': 'Society and Welfare',
                                       'es': 'Sociedad y bienestar'},
                  'type': 'organization'},
 'owner_org': '9d5ac838-6f5e-4e74-8cec-6714ef289887',
 'private': False,
 'relationships_as_object': [],
 'relationships_as_subject': [],
 'resources': [{'api_access_number': '957',
                'api_access_number_absolute': '1942',
                'cache_last_updated': None,
                'cache_url': None,
                'column_types': '',
                'created': '2021-03-25T16:50:43.765583',
                'datastore_active': True,
                'description': '',
                'downloads': '1340',
                'downloads_absolute': '1775',
                'format': 'CSV',
                'hash': '',
                'hide_url': 'Yes',
                'id': '9e135848-eb0a-4bc5-8e60-de558213b3ed',
                'last_modified': '2023-10-31T09:36:27.778810',
                'map_visualization_res': 'data_explorer_map',
                'mimetype': None,
                'mimetype_inner': None,
                'name': 'opendatabcn_sanitat_hospitals-i-centres-atencio-primaria.csv',
                'package_id': 'b959dce3-4862-4697-a158-63f8b15ed4f3',
                'position': 0,
                'qa': "{'updated': '2026-03-25T02:13:29.796882', "
                      "'openness_score': 3, 'archival_timestamp': None, "
                      "'format': u'CSV', 'created': "
                      "'2021-03-26T02:10:12.532627', 'resource_timestamp': "
                      "None, 'openness_score_reason': u'This file had not been "
                      'downloaded at the time of scoring it. URL extension '
                      '"csv" relates to format "CSV" and receives score: 3.\'}',
                'resource_type': None,
                'revision_id': 'e41dc1d6-393f-4755-a734-52b5305e52c2',
                'size': '134288',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/b959dce3-4862-4697-a158-63f8b15ed4f3/resource/9e135848-eb0a-4bc5-8e60-de558213b3ed/download',
                'url_type': None},
               {'api_access_number': '1',
                'api_access_number_absolute': '2',
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2021-06-03T13:52:12.040684',
                'datastore_active': False,
                'description': '',
                'downloads': '1312',
                'downloads_absolute': '1475',
                'format': 'JSON',
                'hash': '',
                'hide_url': 'Yes',
                'id': '6256b00e-623c-4254-8daa-b39bd1eccdd3',
                'last_modified': '2023-10-31T09:36:42.579501',
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': 'opendatabcn_sanitat_hospitals-i-centres-atencio-primaria-js.json',
                'package_id': 'b959dce3-4862-4697-a158-63f8b15ed4f3',
                'position': 1,
                'qa': "{'updated': '2026-03-25T02:13:29.826072', "
                      "'openness_score': 3, 'archival_timestamp': None, "
                      "'format': u'JSON', 'created': "
                      "'2021-06-04T02:10:01.293377', 'resource_timestamp': "
                      "None, 'openness_score_reason': u'This file had not been "
                      'downloaded at the time of scoring it. URL extension '
                      '"json" relates to format "JSON" and receives score: '
                      "3.'}",
                'resource_type': None,
                'revision_id': 'e41dc1d6-393f-4755-a734-52b5305e52c2',
                'size': '7642478',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/b959dce3-4862-4697-a158-63f8b15ed4f3/resource/6256b00e-623c-4254-8daa-b39bd1eccdd3/download',
                'url_type': None}],

In [ ]:
#Saving data in 'items' object
items = data_search["result"]["results"]

#Visualising the content
pprint.pprint(items[0].keys())

dict_keys(['notes_translated', 'geolocation', 'code', 'url_tornada', 'dataset_fields_description', 'fuente', 'private', 'num_tags', 'api', 'frequency', 'id', 'title_translated', 'metadata_modified', 'author', 'author_email', 'isopen', 'long_format', 'state', 'version', 'mar_od', 'relationships_as_object', 'department', 'creator_user_id', 'type', 'resources', 'token_required', 'decalatgeNum', 'tags', 'ODS_Principal_agenda_2030', 'fecha_publicacion', 'ODS_Colateral2_agenda_2030', 'ODS_Colateral1_agenda_2030', 'license_id', 'hide_url', 'relationships_as_subject', 'license_title', 'groups', 'num_resources', 'organization', 'name', 'url', 'notes', 'owner_org', 'load_type', 'tag', 'license_url', 'historical', 'title', 'revision_id', 'extras'])

In [91]:
#Visualising the fields and records inside
for k in items[0].keys():
    print(f" {k}: {items[0][k]}")

 notes_translated: {'ca': 'Informació de les farmàcies de la ciutat de Barcelona.', 'en': 'Information on the pharmacies of the city of Barcelona.', 'es': 'Información de las farmacias de la ciudad de Barcelona.'}
 geolocation: Yes_with_map_view
 code: sanitat farmacies
 url_tornada: {'ca': 'https://w33.bcn.cat/planolBCN/ca', 'en': 'https://w33.bcn.cat/planolBCN/en', 'es': 'https://w33.bcn.cat/planolBCN/es'}
 dataset_fields_description:
 fuente: Ajuntament de Barcelona
 private: False
 num_tags: 4
 api: Yes
 frequency: SETMANAL
 id: 3b65cc32-2299-4638-8050-e9349a2b6ca0
 title_translated: {'ca': 'Farmàcies de la ciutat de Barcelona', 'en': 'Pharmacies in the city of Barcelona', 'es': 'Farmacias de la ciudad de Barcelona'}
 metadata_modified: 2023-10-31T08:35:45.017283
 author: Gerència d'Àrea Agenda 2030, Transició Digital i Esports
 author_email: None
 isopen: True
 long_format: No
 state: active
 version:
 mar_od: No
 relationships_as_object: []
 department: Direcció de Serveis d'Informació i Atenció Ciutadana
 creator_user_id: f4b16b79-1c06-43ee-a5e9-b3df1316fcad
 type: dataset
 resources: [{'cache_last_updated': None, 'token_type': '', 'package_id': '3b65cc32-2299-4638-8050-e9349a2b6ca0', 'datastore_active': True, 'id': 'b89329ea-81ea-496c-9cd0-6758336e6c20', 'size': '917588', 'state': 'active', 'api_access_number': '280', 'api_access_number_absolute': '329', 'token_required': 'No', 'hash': '', 'description': '', 'format': 'CSV', 'downloads': '1766', 'mimetype_inner': None, 'url_type': None, 'token_provider': '', 'column_types': '', 'hide_url': 'Yes', 'mimetype': None, 'cache_url': None, 'name': 'opendatabcn_sanitat_farmacies.csv', 'created': '2021-03-25T16:45:18.720828', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3b65cc32-2299-4638-8050-e9349a2b6ca0/resource/b89329ea-81ea-496c-9cd0-6758336e6c20/download', 'downloads_absolute': '2323', 'map_visualization_res': 'data_explorer_map', 'qa': '{\'updated\': \'2026-03-25T02:13:29.308997\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2021-03-26T02:10:12.111634\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': '2023-10-31T09:35:28.912729', 'position': 0, 'revision_id': 'dfbba2b5-7370-4162-9315-1ff594415107', 'resource_type': None}, {'cache_last_updated': None, 'token_type': '', 'package_id': '3b65cc32-2299-4638-8050-e9349a2b6ca0', 'datastore_active': False, 'id': 'f4fe5904-0214-4e86-a62f-9e03a5dcceaa', 'size': '47299779', 'state': 'active', 'api_access_number': '2', 'api_access_number_absolute': '2', 'token_required': 'No', 'hash': '', 'description': '', 'format': 'JSON', 'downloads': '1220', 'mimetype_inner': None, 'url_type': None, 'token_provider': '', 'hide_url': 'Yes', 'mimetype': None, 'cache_url': None, 'name': 'opendatabcn_sanitat_farmacies-js.json', 'created': '2021-06-03T13:50:58.693341', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3b65cc32-2299-4638-8050-e9349a2b6ca0/resource/f4fe5904-0214-4e86-a62f-9e03a5dcceaa/download', 'downloads_absolute': '1495', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-03-25T02:13:29.334594\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'JSON\', \'created\': \'2021-06-04T02:10:00.879401\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.\'}', 'last_modified': '2023-10-31T09:35:44.984410', 'position': 1, 'revision_id': 'dfbba2b5-7370-4162-9315-1ff594415107', 'resource_type': None}]
 token_required: No
 decalatgeNum: N/A
 tags: [{'vocabulary_id': None, 'state': 'active', 'display_name': 'Farmàcies', 'id': '82ea6d17-1d86-4a34-8d0d-8e9eb31e18a6', 'name': 'Farmàcies'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Plànol BCN', 'id': 'f5a5a7bb-56eb-4380-9e36-18c473662f33', 'name': 'Plànol BCN'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Sanitat', 'id': 'b6ddcdbc-db70-4c48-b796-d5158601f444', 'name': 'Sanitat'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Serveis sanitaris', 'id': '6ba2455b-a0c8-4910-8946-e14253ae9ea7', 'name': 'Serveis sanitaris'}]
 ODS_Principal_agenda_2030: ODS 3: Salut i benestar
 fecha_publicacion: 2019-05-21
 ODS_Colateral2_agenda_2030: N/A
 ODS_Colateral1_agenda_2030: N/A
 license_id: CC-BY-4.0
 hide_url: Yes
 relationships_as_subject: []
 license_title: Creative Commons Attribution 4.0
 groups: []
 num_resources: 2
 organization: {'code': 'societat-i-benestar', 'display_name': 'Societat i benestar', 'description': 'Society and Welfare', 'parent': {'code': 'poblacio', 'display_name': 'Població', 'description': 'Population', 'created': '2017-01-24T16:55:07.191598', 'package_count': 0, 'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon2-poblacio', 'description_translated': {'ca': 'Població', 'en': 'Population', 'es': 'Población'}, 'name': 'poblacio', 'is_organization': True, 'state': 'active', 'image_url': 'bcn-icon2-poblacio', 'groups': [], 'type': 'organization', 'title': 'Population', 'revision_id': 'e0b0ec67-528e-4be2-9425-f9d0bc3c0f71', 'title_translated': {'ca': 'Població', 'en': 'Population', 'es': 'Población'}, 'num_followers': 0, 'id': '3fa4d9dd-5e2c-46fa-ba43-298b6900bb5f', 'approval_status': 'approved'}, 'created': '2017-01-24T16:55:06.300630', 'package_count': 27, 'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon-families', 'tematica_nti': 'sociedad-bienestar', 'description_translated': {'ca': 'Societat i benestar', 'en': 'Society and Welfare', 'es': 'Sociedad y bienestar'}, 'name': 'societat-i-benestar', 'is_organization': True, 'state': 'active', 'image_url': 'bcn-icon-families', 'groups': [{'capacity': 'public', 'name': 'poblacio'}], 'type': 'organization', 'title': 'Society and Welfare', 'revision_id': '614cab6b-639b-49e5-a52c-446758902756', 'title_translated': {'ca': 'Societat i benestar', 'en': 'Society and Welfare', 'es': 'Sociedad y bienestar'}, 'num_followers': 0, 'id': '9d5ac838-6f5e-4e74-8cec-6714ef289887', 'approval_status': 'approved'}
 name: sanitat-farmacies
 url: None
 notes: Information on the pharmacies of the city of Barcelona.
 owner_org: 9d5ac838-6f5e-4e74-8cec-6714ef289887
 load_type: link_extern
 tag: Sanitat,Farmàcies,Serveis sanitaris,Plànol BCN
 license_url: https://creativecommons.org/licenses/by/4.0/
 historical: No
 title: Pharmacies in the city of Barcelona
 revision_id: a4a7c4b3-ed76-4b13-81a7-59d70732be6c
 extras: [{'key': '*00.', 'value': '__ESTRUCTURA RECURS FORMAT .CSV__'}, {'key': '*01.', 'value': "Consultar __'Definició de camps'__ al dataset __[ Miradors a la ciutat de Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/np-nasia-miradors)__"}, {'key': '00.', 'value': '__ESTRUCTURA RECURS EN FORMAT .JSON__'}, {'key': '01.', 'value': "Consultar __'Definició de camps'__ al dataset __[LLista d'esdeveniments diaris de la ciutat de Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/agenda-diaria)__  "}]

In [93]:
#There following fields were selected for further decision-making: 'title', 'format', 'id' and 'package_id' in 'resources'
for j in range(len(items)):
    for i in range(len(items[j]["resources"])):
        print(f"{items[j]["title"]} / {items[j]["resources"][i]["format"]} / {items[j]["resources"][i]["id"]} / {items[j]["resources"][i]["package_id"]}")

Pharmacies in the city of Barcelona / CSV / b89329ea-81ea-496c-9cd0-6758336e6c20 / 3b65cc32-2299-4638-8050-e9349a2b6ca0
Pharmacies in the city of Barcelona / JSON / f4fe5904-0214-4e86-a62f-9e03a5dcceaa / 3b65cc32-2299-4638-8050-e9349a2b6ca0
Hospitals and primary health services of the city of Barcelona / CSV / 9e135848-eb0a-4bc5-8e60-de558213b3ed / b959dce3-4862-4697-a158-63f8b15ed4f3
Hospitals and primary health services of the city of Barcelona / JSON / 6256b00e-623c-4254-8daa-b39bd1eccdd3 / b959dce3-4862-4697-a158-63f8b15ed4f3
Family planning help services of the city of Barcelona / CSV / 1d15d6b6-88fd-4b18-bcad-998e388a478b / f02eadf2-1ab0-40db-ad10-4eb78cb435d0
Family planning help services of the city of Barcelona / JSON / 890a2daa-56ca-4901-b952-d7d8fe891e79 / f02eadf2-1ab0-40db-ad10-4eb78cb435d0
List of health equipments in the city of Barcelona / CSV / 2bf62aa3-63c8-4177-b57a-e32a8c7eb275 / 9c3035c3-2a5f-4fc0-8162-c20563ae5375
List of health equipments in the city of Barcelona / JSON / a32e5f06-4f8c-43e5-a084-7e31d9f33540 / 9c3035c3-2a5f-4fc0-8162-c20563ae5375

In [ ]:
#These data can be used for further identification of the dataset ID as metadata
available_sets_titles = []
available_sets_formats = []
available_sets_resources = []
available_sets_packages = []
for j in range(len(items)):
    for i in range(len(items[j]["resources"])):
        available_sets_titles.append(items[j]["title"].strip())
        available_sets_formats.append(items[j]["resources"][i]["format"].strip())
        available_sets_resources.append(items[j]["resources"][i]["id"].strip())
        available_sets_packages.append(items[j]["resources"][i]["package_id"].strip())

#Creating dataframe of the interested fields
available_sets = pd.DataFrame({
    "Title": available_sets_titles,
    "Resource": available_sets_resources,
    "Package": available_sets_packages,
    "Format": available_sets_formats
})
display(available_sets)

,Title,Resource,Package,Format
0,Pharmacies in the city of Barcelona,b89329ea-81ea-496c-9cd0-6758336e6c20,3b65cc32-2299-4638-8050-e9349a2b6ca0,CSV
1,Pharmacies in the city of Barcelona,f4fe5904-0214-4e86-a62f-9e03a5dcceaa,3b65cc32-2299-4638-8050-e9349a2b6ca0,JSON
2,Hospitals and primary health services of the c...,9e135848-eb0a-4bc5-8e60-de558213b3ed,b959dce3-4862-4697-a158-63f8b15ed4f3,CSV
3,Hospitals and primary health services of the c...,6256b00e-623c-4254-8daa-b39bd1eccdd3,b959dce3-4862-4697-a158-63f8b15ed4f3,JSON
4,Family planning help services of the city of B...,1d15d6b6-88fd-4b18-bcad-998e388a478b,f02eadf2-1ab0-40db-ad10-4eb78cb435d0,CSV
5,Family planning help services of the city of B...,890a2daa-56ca-4901-b952-d7d8fe891e79,f02eadf2-1ab0-40db-ad10-4eb78cb435d0,JSON
6,List of health equipments in the city of Barce...,2bf62aa3-63c8-4177-b57a-e32a8c7eb275,9c3035c3-2a5f-4fc0-8162-c20563ae5375,CSV
7,List of health equipments in the city of Barce...,a32e5f06-4f8c-43e5-a084-7e31d9f33540,9c3035c3-2a5f-4fc0-8162-c20563ae5375,JSON

2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

In [ ]:
#Search the dataframe for the ID of the resource related to Pharmacies
resource_selected = available_sets[(available_sets["Title"].str.contains('pharmac',case=False,  na=False)) & (available_sets["Format"]=='CSV')]
print(resource_selected)

                                 Title                              Resource  \
0  Pharmacies in the city of Barcelona  b89329ea-81ea-496c-9cd0-6758336e6c20

                                Package Format
0  3b65cc32-2299-4638-8050-e9349a2b6ca0    CSV

3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

Recuperar almenys 100 registres.

In [97]:
url = f"https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id={resource_selected['Resource'][0]}&limit=100"
farmaco_data = requests.get(url)
print(farmaco_data.status_code)
farmaco_json = farmaco_data.json()

200

In [100]:
#Checking the fields in this resource
for i in range(len(farmaco_json['result'].keys())):
    for k in farmaco_json['result'].keys():
        pprint.pprint(farmaco_json['result'][k], sort_dicts=False)

'b89329ea-81ea-496c-9cd0-6758336e6c20'
[{'type': 'int4', 'id': '_id'},
 {'type': 'text', 'id': 'register_id'},
 {'type': 'text', 'id': 'name'},
 {'type': 'text', 'id': 'institution_id'},
 {'type': 'text', 'id': 'institution_name'},
 {'type': 'timestamp', 'id': 'created'},
 {'type': 'timestamp', 'id': 'modified'},
 {'type': 'text', 'id': 'addresses_roadtype_id'},
 {'type': 'text', 'id': 'addresses_roadtype_name'},
 {'type': 'numeric', 'id': 'addresses_road_id'},
 {'type': 'text', 'id': 'addresses_road_name'},
 {'type': 'numeric', 'id': 'addresses_start_street_number'},
 {'type': 'numeric', 'id': 'addresses_end_street_number'},
 {'type': 'numeric', 'id': 'addresses_neighborhood_id'},
 {'type': 'text', 'id': 'addresses_neighborhood_name'},
 {'type': 'numeric', 'id': 'addresses_district_id'},
 {'type': 'text', 'id': 'addresses_district_name'},
 {'type': 'numeric', 'id': 'addresses_zip_code'},
 {'type': 'text', 'id': 'addresses_town'},
 {'type': 'text', 'id': 'addresses_main_address'},
 {'type': 'text', 'id': 'addresses_type'},
 {'type': 'numeric', 'id': 'values_id'},
 {'type': 'numeric', 'id': 'values_attribute_id'},
 {'type': 'text', 'id': 'values_category'},
 {'type': 'text', 'id': 'values_attribute_name'},
 {'type': 'text', 'id': 'values_value'},
 {'type': 'text', 'id': 'values_outstanding'},
 {'type': 'text', 'id': 'values_description'},
 {'type': 'numeric', 'id': 'secondary_filters_id'},
 {'type': 'text', 'id': 'secondary_filters_name'},
 {'type': 'text', 'id': 'secondary_filters_fullpath'},
 {'type': 'numeric', 'id': 'secondary_filters_tree'},
 {'type': 'numeric', 'id': 'secondary_filters_asia_id'},
 {'type': 'numeric', 'id': 'geo_epgs_25831_x'},
 {'type': 'numeric', 'id': 'geo_epgs_25831_y'},
 {'type': 'numeric', 'id': 'geo_epgs_4326_lat'},
 {'type': 'numeric', 'id': 'geo_epgs_4326_lon'},
 {'type': 'text', 'id': 'estimated_dates'},
 {'type': 'text', 'id': 'start_date'},
 {'type': 'text', 'id': 'end_date'},
 {'type': 'text', 'id': 'timetable'}]
[{'addresses_roadtype_name': '',
  'addresses_end_street_number': '25',
  'geo_epgs_4326_lon': '2.207576493108837',
  'values_attribute_name': 'Tel.',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer del Paraguai',
  'values_category': 'Telèfons',
  'addresses_zip_code': '8020',
  'secondary_filters_id': '61732068',
  'values_value': '930117177',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': 'Farmàcies',
  'timetable': '',
  'secondary_filters_tree': '651',
  'start_date': '',
  'addresses_district_name': 'Sant Martí',
  'end_date': '',
  'geo_epgs_25831_x': '433777.79',
  'addresses_start_street_number': '25',
  'register_id': '\ufeff99400748841',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '10',
  'addresses_roadtype_id': '',
  'addresses_type': '',
  'addresses_neighborhood_id': '71',
  '_id': 1,
  'name': 'Farmàcia Sallent - Morillo',
  'addresses_road_id': '244800',
  'created': '2024-12-04T12:16:07.369842',
  'geo_epgs_25831_y': '4585384.823',
  'institution_name': '',
  'modified': '2025-07-08T09:36:38.918877',
  'secondary_filters_asia_id': '65103008001000',
  'secondary_filters_fullpath': 'Planol BCN >> Sanitat >> Farmàcies >> '
                                'Farmàcies',
  'geo_epgs_4326_lat': '41.41728976779675',
  'values_description': '',
  'values_id': '642510',
  'addresses_neighborhood_name': 'Provençals del Poblenou',
  'values_outstanding': 'True',
  'values_attribute_id': '20001'},
 {'addresses_roadtype_name': '',
  'addresses_end_street_number': '186',
  'geo_epgs_4326_lon': '2.1526146544603253',
  'values_attribute_name': 'Tel.',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer del Comte Borrell',
  'values_category': 'Telèfons',
  'addresses_zip_code': '8029',
  'secondary_filters_id': '61732068',
  'values_value': '934530687',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': 'Farmàcies',
  'timetable': '',
  'secondary_filters_tree': '651',
  'start_date': '',
  'addresses_district_name': 'Eixample',
  'end_date': '',
  'geo_epgs_25831_x': '429149.648',
  'addresses_start_street_number': '186',
  'register_id': '\ufeff99400748504',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '2',
  'addresses_roadtype_id': '',
  'addresses_type': '',
  'addresses_neighborhood_id': '9',
  '_id': 2,
  'name': 'Farmàcia Alabern Ros',
  'addresses_road_id': '87009',
  'created': '2024-12-02T10:13:03.698326',
  'geo_epgs_25831_y': '4581851.849',
  'institution_name': '',
  'modified': '2024-12-02T10:14:12.020393',
  'secondary_filters_asia_id': '65103008001000',
  'secondary_filters_fullpath': 'Planol BCN >> Sanitat >> Farmàcies >> '
                                'Farmàcies',
  'geo_epgs_4326_lat': '41.38507487276931',
  'values_description': '',
  'values_id': '641677',
  'addresses_neighborhood_name': "la Nova Esquerra de l'Eixample",
  'values_outstanding': 'True',
  'values_attribute_id': '20001'},
 {'addresses_roadtype_name': '',
  'addresses_end_street_number': None,
  'geo_epgs_4326_lon': '2.1689919445528485',
  'values_attribute_name': 'Tel.',
  'estimated_dates': '',
  'addresses_road_name': 'C Pedrell',
  'values_category': 'Telèfons',
  'addresses_zip_code': '8032',
  'secondary_filters_id': '61732068',
  'values_value': '933573046',
  'addresses_town': 'BARCELONA',
  'secondary_filters_name': 'Farmàcies',
  'timetable': '',
  'secondary_filters_tree': '651',
  'start_date': '',
  'addresses_district_name': 'Horta-Guinardó',
  'end_date': '',
  'geo_epgs_25831_x': '430560.4580782837',
  'addresses_start_street_number': '1',
  'register_id': '\ufeff99400219496',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '7',
  'addresses_roadtype_id': '',
  'addresses_type': '',
  'addresses_neighborhood_id': '36',
  '_id': 3,
  'name': 'Farmàcia Ortiz de Saracho Mata',
  'addresses_road_id': '248800',
  'created': '2009-01-12T19:11:08',
  'geo_epgs_25831_y': '4586162.897105979',
  'institution_name': '',
  'modified': '2024-11-29T10:19:23.855498',
  'secondary_filters_asia_id': '65103008001000',
  'secondary_filters_fullpath': 'Planol BCN >> Sanitat >> Farmàcies >> '
                                'Farmàcies',
  'geo_epgs_4326_lat': '41.42402601123394',
  'values_description': '',
  'values_id': '221981',
  'addresses_neighborhood_name': "la Font d'en Fargues",
  'values_outstanding': 'True',
  'values_attribute_id': '20001'},
 {'addresses_roadtype_name': '',
  'addresses_end_street_number': None,
  'geo_epgs_4326_lon': '2.1734956861885055',
  'values_attribute_name': 'Tel.',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer del Doctor Pi i Molist',
  'values_category': 'Telèfons',
  'addresses_zip_code': '8016',
  'secondary_filters_id': '61732068',
  'values_value': '934080293',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': 'Farmàcies',
  'timetable': '',
  'secondary_filters_tree': '651',
  'start_date': '',
  'addresses_district_name': 'Nou Barris',
  'end_date': '',
  'geo_epgs_25831_x': '430946.38112643064',
  'addresses_start_street_number': '66',
  'register_id': '\ufeff92086018569',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '8',
  'addresses_roadtype_id': '',
  'addresses_type': '',
  'addresses_neighborhood_id': '45',
  '_id': 4,
  'name': 'Farmàcia Mestre Rovira',
  'addresses_road_id': '103003',
  'created': '1987-02-09T00:00:00',
  'geo_epgs_25831_y': '4587163.349436222',
  'institution_name': '',
  'modified': '2024-12-05T11:53:19.107038',
  'secondary_filters_asia_id': '65103008001000',
  'secondary_filters_fullpath': 'Planol BCN >> Sanitat >> Farmàcies >> '
                                'Farmàcies',
  'geo_epgs_4326_lat': '41.43306997716273',
  'values_description': '',
  'values_id': '166293',
  'addresses_neighborhood_name': 'Porta',
  'values_outstanding': 'True',
  'values_attribute_id': '20001'},
 {'addresses_roadtype_name': '',
  'addresses_end_street_number': '290',
  'geo_epgs_4326_lon': '2.20036288238702',
  'values_attribute_name': 'Tel.',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer de Puigcerdà',
  'values_category': 'Telèfons',
  'addresses_zip_code': '8020',
  'secondary_filters_id': '61732068',
  'values_value': '936763612',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': 'Farmàcies',
  'timetable': '',
  'secondary_filters_tree': '651',
  'start_date': '',
  'addresses_district_name': 'Sant Martí',
  'end_date': '',
  'geo_epgs_25831_x': '433181.66599999997',
  'addresses_start_street_number': '290',
  'register_id': '\ufeff92086018601',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '10',
  'addresses_roadtype_id': '',
  'addresses_type': '',
  'addresses_neighborhood_id': '73',
  '_id': 5,
  'name': 'Farmàcia Cano Valenciano',
  'addresses_road_id': '270107',
  'created': '1987-02-10T00:00:00',
  'geo_epgs_25831_y': '4586117.768',
  'institution_name': '',
  'modified': '2024-12-04T11:48:05.579893',
  'secondary_filters_asia_id': '65103008001000',
  'secondary_filters_fullpath': 'Planol BCN >> Sanitat >> Farmàcies >> '
                                'Farmàcies',
  'geo_epgs_4326_lat': '41.42384183548677',
  'values_description': '',
  'values_id': '166295',
  'addresses_neighborhood_name': 'la Verneda i la Pau',
  'values_outstanding': 'True',
  'values_attribute_id': '20001'},
 {'addresses_roadtype_name': '',
  'addresses_end_street_number': None,
  'geo_epgs_4326_lon': '2.1627388233484495',
  'values_attribute_name': 'Tel.',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer del Comte Borrell',
  'values_category': 'Telèfons',
  'addresses_zip_code': '8015',
  'secondary_filters_id': '61732068',
  'values_value': '934410211',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': 'Farmàcies',
  'timetable': '',
  'secondary_filters_tree': '651',
  'start_date': '',
  'addresses_district_name': 'Eixample',
  'end_date': '',
  'geo_epgs_25831_x': '429987.67671990546',
  'addresses_start_street_number': '43',
  'register_id': '\ufeff75990041421',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '2',
  'addresses_roadtype_id': '',
  'addresses_type': '',
  'addresses_neighborhood_id': '10',
  '_id': 6,
  'name': 'Farmàcia Balañá Vives',
  'addresses_road_id': '87009',
  'created': '1996-09-18T00:00:00',
  'geo_epgs_25831_y': '4580967.262663954',
  'institution_name': '',
  'modified': '2024-12-05T13:17:19.627347',
  'secondary_filters_asia_id': '65103008001000',
  'secondary_filters_fullpath': 'Planol BCN >> Sanitat >> Farmàcies >> '
                                'Farmàcies',
  'geo_epgs_4326_lat': '41.3771810586829',
  'values_description': '',
  'values_id': '137785',
  'addresses_neighborhood_name': 'Sant Antoni',
  'values_outstanding': 'True',
  'values_attribute_id': '20001'},
 {'addresses_roadtype_name': '',
  'addresses_end_street_number': None,
  'geo_epgs_4326_lon': '2.1311762923225688',
  'values_attribute_name': 'Tel.',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer de Ganduxer',
  'values_category': 'Telèfons',
  'addresses_zip_code': '8022',
  'secondary_filters_id': '61732068',
  'values_value': '934176021',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': 'Farmàcies',
  'timetable': '',
  'secondary_filters_tree': '651',
  'start_date': '',
  'addresses_district_name': 'Sarrià-Sant Gervasi',
  'end_date': '',
  'geo_epgs_25831_x': '427377.1944774692',
  'addresses_start_street_number': '129',
  'register_id': '\ufeff75990050202',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '5',
  'addresses_roadtype_id': '',
  'addresses_type': '',
  'addresses_neighborhood_id': '24',
  '_id': 7,
  'name': 'Farmàcia Martín Leiva',
  'addresses_road_id': '139805',
  'created': '1996-09-18T00:00:00',
  'geo_epgs_25831_y': '4583867.78081307',
  'institution_name': '',
  'modified': '2026-01-14T09:39:48.269961',
  'secondary_filters_asia_id': '65103008001000',
  'secondary_filters_fullpath': 'Planol BCN >> Sanitat >> Farmàcies >> '
                                'Farmàcies',
  'geo_epgs_4326_lat': '41.403073477422204',
  'values_description': '',
  'values_id': '137601',
  'addresses_neighborhood_name': 'les Tres Torres',
  'values_outstanding': 'True',
  'values_attribute_id': '20001'},
 {'addresses_roadtype_name': '',
  'addresses_end_street_number': None,
  'geo_epgs_4326_lon': '2.186200825134386',
  'values_attribute_name': 'Tel.',
  'estimated_dates': '',
  'addresses_road_name': 'Avinguda Meridiana',
  'values_category': 'Telèfons',
  'addresses_zip_code': '8027',
  'secondary_filters_id': '61732068',
  'values_value': '933118651',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': 'Farmàcies',
  'timetable': '',
  'secondary_filters_tree': '651',
  'start_date': '',
  'addresses_district_name': 'Sant Andreu',
  'end_date': '',
  'geo_epgs_25831_x': '432001.3990285661',
  'addresses_start_street_number': '344',
  'register_id': '\ufeff92086018652',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '9',
  'addresses_roadtype_id': '',
  'addresses_type': '',
  'addresses_neighborhood_id': '61',
  '_id': 8,
  'name': 'Farmàcia Fernández Rodriguez',
  'addresses_road_id': '209900',
  'created': '1987-02-10T00:00:00',
  'geo_epgs_25831_y': '4586462.48647902',
  'institution_name': '',
  'modified': '2024-12-02T15:11:25.034140',
  'secondary_filters_asia_id': '65103008001000',
  'secondary_filters_fullpath': 'Planol BCN >> Sanitat >> Farmàcies >> '
                                'Farmàcies',
  'geo_epgs_4326_lat': '41.42684756652579',
  'values_description': '',
  'values_id': '166300',
  'addresses_neighborhood_name': 'la Sagrera',
  'values_outstanding': 'True',
  'values_attribute_id': '20001'},
 {'addresses_roadtype_name': '',
  'addresses_end_street_number': '510',
  'geo_epgs_4326_lon': '2.1851219585996184',
  'values_attribute_name': 'Tel.',
  'estimated_dates': '',
  'addresses_road_name': 'Avinguda Meridiana',
  'values_category': 'Telèfons',
  'addresses_zip_code': '8030',
  'secondary_filters_id': '61732068',
  'values_value': '933464636',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': 'Farmàcies',
  'timetable': '',
  'secondary_filters_tree': '651',
  'start_date': '',
  'addresses_district_name': 'Sant Andreu',
  'end_date': '',
  'geo_epgs_25831_x': '431922.277',
  'addresses_start_street_number': '506',
  'register_id': '\ufeff92086018735',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '9',
  'addresses_roadtype_id': '',
  'addresses_type': '',
  'addresses_neighborhood_id': '60',
  '_id': 9,
  'name': 'Farmàcia Subietas Mesalles',
  'addresses_road_id': '209900',
  'created': '1987-02-13T00:00:00',
  'geo_epgs_25831_y': '4587634.772',
  'institution_name': '',
  'modified': '2026-01-12T17:02:49.192990',
  'secondary_filters_asia_id': '65103008001000',
  'secondary_filters_fullpath': 'Planol BCN >> Sanitat >> Farmàcies >> '
                                'Farmàcies',
  'geo_epgs_4326_lat': '41.43739922821013',
  'values_description': '',
  'values_id': '166313',
  'addresses_neighborhood_name': 'Sant Andreu',
  'values_outstanding': 'True',
  'values_attribute_id': '20001'},
 {'addresses_roadtype_name': '',
  'addresses_end_street_number': None,
  'geo_epgs_4326_lon': '2.2204504400748277',
  'values_attribute_name': 'Tel.',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer de Sant Ramon de Penyafort',
  'values_category': 'Telèfons',
  'addresses_zip_code': '8019',
  'secondary_filters_id': '61732068',
  'values_value': '933580900',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': 'Farmàcies',
  'timetable': '',
  'secondary_filters_tree': '651',
  'start_date': '',
  'addresses_district_name': 'Sant Martí',
  'end_date': '',
  'geo_epgs_25831_x': '434850.117661059',
  'addresses_start_street_number': '3',
  'register_id': '\ufeff75990017099',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '10',
  'addresses_roadtype_id': '',
  'addresses_type': '',
  'addresses_neighborhood_id': '70',
  '_id': 10,
  'name': 'Farmàcia Puga Gasull',
  'addresses_road_id': '310201',
  'created': '1996-09-17T00:00:00',
  'geo_epgs_25831_y': '4584981.048479498',
  'institution_name': '',
  'modified': '2024-12-04T12:36:08.018501',
  'secondary_filters_asia_id': '65103008001000',
  'secondary_filters_fullpath': 'Planol BCN >> Sanitat >> Farmàcies >> '
                                'Farmàcies',
  'geo_epgs_4326_lat': '41.41374072715184',
  'values_description': '',
  'values_id': '135155',
  'addresses_neighborhood_name': 'el Besòs i el Maresme',
  'values_outstanding': 'True',
  'values_attribute_id': '20001'},
 {'addresses_roadtype_name': '',
  'addresses_end_street_number': '154',
  'geo_epgs_4326_lon': '2.1668500276389375',
  'values_attribute_name': 'Tel.',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer de Cartellà',
  'values_category': 'Telèfons',
  'addresses_zip_code': '8031',
  'secondary_filters_id': '61732068',
  'values_value': '936819389',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': 'Farmàcies',
  'timetable': '',
  'secondary_filters_tree': '651',
  'start_date': '',
  'addresses_district_name': 'Nou Barris',
  'end_date': '',
  'geo_epgs_25831_x': '430387.192',
  'addresses_start_street_number': '150',
  'register_id': '\ufeff75990052556',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '8',
  'addresses_roadtype_id': '',
  'addresses_type': '',
  'addresses_neighborhood_id': '44',
  '_id': 11,
  'name': 'Farmàcia Barrachina Canovas',
  'addresses_road_id': '69109',
  'created': '1996-09-18T00:00:00',
  'geo_epgs_25831_y': '4586758.608',
  'institution_name': '',
  'modified': '2024-12-16T13:21:10.778365',
  'secondary_filters_asia_id': '65103008001000',
  'secondary_filters_fullpath': 'Planol BCN >> Sanitat >> Farmàcies >> '
                                'Farmàcies',
  'geo_epgs_4326_lat': '41.429376355154055',
  'values_description': '',
  'values_id': '138095',
  'addresses_neighborhood_name': 'Vilapicina i la Torre Llobeta',
  'values_outstanding': 'True',
  'values_attribute_id': '20001'},
 {'addresses_roadtype_name': '',
  'addresses_end_street_number': None,
  'geo_epgs_4326_lon': '2.1132760937599184',
  'values_attribute_name': 'Tel.',
  'estimated_dates': '',
  'addresses_road_name': 'Pisuerga',
  'values_category': 'Telèfons',
  'addresses_zip_code': '8028',
  'secondary_filters_id': '61732068',
  'values_value': '933333048',
  'addresses_town': 'BARCELONA',
  'secondary_filters_name': 'Farmàcies',
  'timetable': '',
  'secondary_filters_tree': '651',
  'start_date': '',
  'addresses_district_name': 'Les Corts',
  'end_date': '',
  'geo_epgs_25831_x': '425851.64692575776',
  'addresses_start_street_number': '20',
  'register_id': '\ufeff75990095308',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '4',
  'addresses_roadtype_id': '',
  'addresses_type': '',
  'addresses_neighborhood_id': '20',
  '_id': 12,
  'name': 'Farmàcia Garcia Rico',
  'addresses_road_id': '238035',
  'created': '1996-09-18T00:00:00',
  'geo_epgs_25831_y': '4581019.827268898',
  'institution_name': '',
  'modified': '2024-12-02T12:37:08.485215',
  'secondary_filters_asia_id': '65103008001000',
  'secondary_filters_fullpath': 'Planol BCN >> Sanitat >> Farmàcies >> '
                                'Farmàcies',
  'geo_epgs_4326_lat': '41.37728400381358',
  'values_description': '',
  'values_id': '141315',
  'addresses_neighborhood_name': 'la Maternitat i Sant Ramon',
  'values_outstanding': 'True',
  'values_attribute_id': '20001'},
 {'addresses_roadtype_name': '',
  'addresses_end_street_number': None,
  'geo_epgs_4326_lon': '2.1899761862864686',

In [101]:
#Checking the keys to identify fields of interest
print(farmaco_json['result'].keys())
#Visualising the content of the 'records'
print(farmaco_json['result']['records'])
#Checking the number of the elements in 'records'
print(len(farmaco_json['result']['records']))
#Checking which fields are inside 'records'
print(farmaco_json['result']['records'][0].keys())

dict_keys(['resource_id', 'fields', 'records', '_links', 'limit', 'total'])

4. Converteix els resultats a un DataFrame.

In [102]:
#Create an empty dataframe with column names from the list of fields in 'records'
datacollect = pd.DataFrame(columns=farmaco_json['result']['records'][0].keys())
#Extracting JSON format of each record and saving it in dataframe by concatenation
for i in range(len(farmaco_json['result']['records'])):
    datacollect = pd.concat(
        [datacollect, pd.DataFrame([farmaco_json['result']['records'][i]])],
        ignore_index=True
    )
print(datacollect.head())

  addresses_roadtype_name addresses_end_street_number   geo_epgs_4326_lon  \
0                                                  25   2.207576493108837
1                                                 186  2.1526146544603253
2                                                None  2.1689919445528485
3                                                None  2.1734956861885055
4                                                 290    2.20036288238702

  values_attribute_name estimated_dates            addresses_road_name  \
0                  Tel.                            Carrer del Paraguai
1                  Tel.                       Carrer del Comte Borrell
2                  Tel.                                      C Pedrell
3                  Tel.                  Carrer del Doctor Pi i Molist
4                  Tel.                            Carrer de Puigcerdà

  values_category addresses_zip_code secondary_filters_id values_value  ...  \
0        Telèfons               8020             61732068    930117177  ...
1        Telèfons               8029             61732068    934530687  ...
2        Telèfons               8032             61732068    933573046  ...
3        Telèfons               8016             61732068    934080293  ...
4        Telèfons               8020             61732068    936763612  ...

  institution_name                    modified secondary_filters_asia_id  \
0                   2025-07-08T09:36:38.918877            65103008001000
1                   2024-12-02T10:14:12.020393            65103008001000
2                   2024-11-29T10:19:23.855498            65103008001000
3                   2024-12-05T11:53:19.107038            65103008001000
4                   2024-12-04T11:48:05.579893            65103008001000

                        secondary_filters_fullpath  geo_epgs_4326_lat  \
0  Planol BCN >> Sanitat >> Farmàcies >> Farmàcies  41.41728976779675
1  Planol BCN >> Sanitat >> Farmàcies >> Farmàcies  41.38507487276931
2  Planol BCN >> Sanitat >> Farmàcies >> Farmàcies  41.42402601123394
3  Planol BCN >> Sanitat >> Farmàcies >> Farmàcies  41.43306997716273
4  Planol BCN >> Sanitat >> Farmàcies >> Farmàcies  41.42384183548677

  values_description values_id     addresses_neighborhood_name  \
0                       642510         Provençals del Poblenou
1                       641677  la Nova Esquerra de l'Eixample
2                       221981            la Font d'en Fargues
3                       166293                           Porta
4                       166295             la Verneda i la Pau

  values_outstanding values_attribute_id
0               True               20001
1               True               20001
2               True               20001
3               True               20001
4               True               20001

[5 rows x 41 columns]

5. Desa el DataFrame en un fitxer .csv.

In [ ]:
#Saving the dataframe into CSV file
datacollect.to_csv("Pharmacies_BCN_extracted.csv", index=False, encoding='utf-8')